### ISSUE TITLE
Content Row

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1009]
**Teaser Thumbnails**
Large teaser, Large teaser alternate should use the same image styles - the wide rectangles that are used in the alternate display
<img width="1041" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/435312c3-7c37-4aec-b8a8-9b7aa6176000">

Thumbnails should align to the top when images are floated to the side
<img width="1531" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/000380ef-745f-4683-b2d0-b1b2b83316a0">

**Feature Display** 
Feature display should only show 3 items, and shouldn't show items that don't have a thumbnail attached.

The screenshot below shows that it's displaying 4 items and the 4th also doesn't have a thumbnail:
<img width="1320" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/a7cd066c-ef1a-4e5d-b6ea-f893ef5373c9">

**Comment by patrickbrown-io** [comment]
Could not replicate the `focal image square` images presenting in "Teaser Large" in a local development. All template code points to these being rendered as `focal image wide`.
