### ISSUE TITLE
Breadcrumb navigation missing separator between items

### ISSUE THREAD

**Issue by TeddyBearX** [CuBoulder/tiamat-theme#101]
The items in the breadcrumb navigation don't have a separator between them and are crammed together. This is noticeable on any non-admin page where the breadcrumb navigation shows multiple parent pages.

**Comment by jcsparks** [comment]
May be able to just pull over the breadcrumb css from the previous theme or at least use that as a starting place.

**Comment by jcsparks** [comment]
Also, the breadcrumb shouldn't be visible on the <front> page.  That likely will require some logic on the page.html.twig template to check if you're on the <front> page before adding in the breadcrumb region.

**Comment by TeddyBearX** [comment]
> Also, the breadcrumb shouldn't be visible on the page. That likely will require some logic on the page.html.twig template to check if you're on the page before adding in the breadcrumb region.

`\Drupal::service('path.matcher')->isFrontPage()` is the only recommended way I've seen to do this but it appears to be returning false when on the homepage for some reason.
