### ISSUE TITLE
Caching Issue

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1018]
I'm working on the new Chancellor's site (https://live-ucbdev-chancellor.pantheonsite.io/) and I'm having caching issues. I updated images on https://live-ucbdev-chancellor.pantheonsite.io/leadership yesterday for Russ and Pat and they're still not showing though I've cleared my own cache. They show in the backend, but not for the front-end user. I used a content grid on a basic page to create this page.

**Comment by jcsparks** [comment]
I'm seeing the images on the site @asvensen .  Are you still having issues?  

<img width="1466" alt="Screenshot 2024-06-04 at 9 23 32 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/12704433/3893c639-43d6-486b-9960-afedc561df3e">

**Comment by jcsparks** [comment]
@jnicholCU worked with Annie to get this one resolved.

**Comment by asvensen** [comment]
As you noted, Joshua helped me sort this out!
