### ISSUE TITLE
URLs not updating when page title and menu title change

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1025]
Working on https://live-ucbdev-chancellor.pantheonsite.io and changed "Communications" to "Outreach" and the URLs for the child pages still reflect the parent as communications and not outreach. See screenshot. 

![Screenshot 2024-06-04 at 10 54 19 AM](https://github.com/CuBoulder/tiamat-theme/assets/153543897/4f8e1811-c36a-433f-8a67-2b47a5d9bc21)

**Comment by jcsparks** [comment]
I believe this is a caching issues.  May be fixed with the addition of a cache clear button/function that we're going to add in.
