### ISSUE TITLE
Back to Top button

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/tiamat-theme#1028]
I do not see the back to top button we used to have on our sites. This is not something a user can configure on the page - correct?
![Back to top](https://github.com/CuBoulder/tiamat-theme/assets/16137919/f673c68d-ba01-4ded-ad78-88edd4886bde)

**Comment by jcsparks** [comment]
Adding to the backlog for the time being.  We can discuss with UI/UX team to determine if this is still needed and if so assign priority relative to other needs.

**Comment by patrickbrown-io** [comment]
Need to figure out config on past sites to replicate in D10. Should be pretty straightforward to add!

**Comment by jcsparks** [comment]
Will not be adding in at this time, may revisit later.
