### ISSUE TITLE
Taxonomy Term not updating on person page

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/tiamat-theme#1030]
I edited a Job Type taxonomy term but it did not fully update on the site.
On the people list page: Displays in the page grouping and filter as updated but not in the summary on the people.
On the Person Page: It displays the old term on the person page but when you edit the person the new term in displayed in the Job Type field.
Can a user clear the site cache? Is this the issue that the site cache needs to be cleared - an hour and a half after the change it is still displaying incorrectly.
![Tax term updating](https://github.com/CuBoulder/tiamat-theme/assets/16137919/7116788e-1395-4ce8-bb57-933128704ba7)
![Tax term updating2](https://github.com/CuBoulder/tiamat-theme/assets/16137919/11bca34b-eb46-4f63-ab37-c0d07d6314c5)
![Tax term updating4](https://github.com/CuBoulder/tiamat-theme/assets/16137919/c0d61e0b-8c9a-47a5-91c5-bdce72e58818)
![Tax term updating3](https://github.com/CuBoulder/tiamat-theme/assets/16137919/b67b6f36-b66f-4bfd-b654-27aeb44294e9)

**Comment by patrickbrown-io** [comment]
Caches the Person page but Person Page uses JSON API so the update is reflected immediately there. Cache clear resolves this issue on the Person Page.
