### ISSUE TITLE
Collection grid not showing all collection items

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#1031]
The full list of collection items are no longer showing on the collection grid blocks. This change happened with the sandbox update yesterday and is across the site. Note: this was an issue previously that had been fixed:

https://live-ucbdev-homepage.pantheonsite.io/

Following are some of the collection grid pages (note, it is happening on every collection grid on the site, this isn't the full list):

https://live-ucbdev-homepage.pantheonsite.io/academics/programs/majors
https://live-ucbdev-homepage.pantheonsite.io/academics/arts-sciences
https://live-ucbdev-homepage.pantheonsite.io/resources

**Comment by timurtripp** [comment]
It appears to be throwing an error in the console. `ReferenceError: aggregatedCategories is not defined`
