### ISSUE TITLE
Navigation and breadcrumbs

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#1032]
When placing a page into the site structure, the parent page should be highlighted and the breadcrumbs should follow the path as we have it working on D7. We have urls that we shorten, the breadcrumbs seem to be following the url structure and not the menu structure of pages. The navigation tabs don't highlight in either case.

These pages are placed under the same menu structure, but the aerospace page url was updated. The url change shouldn't change the breadcrumbs with the page being placed under engineering in the menu structure:

https://live-ucbdev-homepage.pantheonsite.io/academics/engineering/testing-page
![Screenshot 2024-06-05 at 9 21 38 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/2e63c690-1495-4c26-947e-8e967dc62e69)

https://live-ucbdev-homepage.pantheonsite.io/academics/bs-aerospace-engineering
![Screenshot 2024-06-05 at 9 21 49 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/00e90055-75ba-48bd-998f-dcc774989c82)

Also, would like the parent page to be highlighted in any case. It is working properly on this page:
https://live-ucbdev-homepage.pantheonsite.io/academics/arts-sciences
![Screenshot 2024-06-05 at 9 23 43 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/b32a5048-d51e-46ea-a429-3772f8e10d64)

but not on this page, or many others:
https://live-ucbdev-homepage.pantheonsite.io/academics/engineering/testing-page
![Screenshot 2024-06-05 at 9 24 53 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/f6ce33df-c22a-40b7-9b62-e5ff8d087c1c)

**Comment by jcsparks** [comment]
It looks like the `Engineering & Applied Sciences` link on this page : https://live-ucbdev-homepage.pantheonsite.io/academics/engineering/testing-page does have the active class already.  We should be able to get that highlighting as the second item.  

Not sure there's anything we can do about the breadcrumbs though.  I don't believe that D10 breadcrumbs even look at the menu structure and work 100% from the IA in the url structure.
