### ISSUE TITLE
Can't login to D10 sites

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1035]
Whenever I try to login to a D10 site, I get an HTTP 400 Status-Bad Request error. 
![Screenshot 2024-06-05 at 10 55 30 AM](https://github.com/CuBoulder/tiamat-theme/assets/153543897/41e9ec35-9473-4e6f-9f7d-acce70dbce53)

**Comment by jnicholCU** [comment]
Per Annie
> A client had the same issue with https://live-ucbdev-compliance-hub.pantheonsite.io/ last week and I routed her to websupport@colorado.edu. Not sure what happened to it from there and Kevin's out...

**Comment by jnicholCU** [comment]
Solved with simple cache clear
