### ISSUE TITLE
Child Menu Issues

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1039]
When I create a new child page and place it in the menu structure, it shows in the sidebar when I save the page:
![Screenshot 2024-06-06 at 12 02 42 PM](https://github.com/CuBoulder/tiamat-theme/assets/153543897/07b87563-c5de-4226-a0c3-6a907c4e4798)

When I then navigate to the parent, the children don't show:
![Screenshot 2024-06-06 at 12 03 07 PM](https://github.com/CuBoulder/tiamat-theme/assets/153543897/bcfd1fb3-a678-4f36-9531-1c3aa1259935)

**Comment by asvensen** [comment]
This is on https://live-ucbdev-sandbox-webcentral-101.pantheonsite.io/homepage (no clue why the homepage has "homepage" in the URL).

**Comment by jcsparks** [comment]
I thought this was how it was supposed to work.

**Comment by asvensen** [comment]
We definitely want to see child pages when on the parent.

**Comment by asvensen** [comment]
And now they're showing. Must be a part of the caching issue.
