### ISSUE TITLE
Rise menu style breaks with multiple items in the menu.

### ISSUE THREAD

**Issue by jacob-korf** [CuBoulder/tiamat-theme#1057]
The rise menu styles currently has issues with screen sizing when there are multiple links in the menus.
<img width="949" alt="Screenshot 2024-06-12 at 2 35 12 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/56124082/b693ae1f-c918-4917-8ee2-348de213e180">

**Comment by jcsparks** [comment]
Working now.
