### ISSUE TITLE
People List Page breaking on some data

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#1065]
Sure what's breaking it, but suspect we have some data that's causing an issue for the People List node on this site : https://live-ucbprod-anthropology.pantheonsite.io/our-peeps

There should be dozens of people on this example Person List node.  Sorry I can't be more specific about where it's breaking.

**Comment by patrickbrown-io** [comment]
TypeError: Cannot read properties of undefined (reading 'name')
    at PeopleListElement.getTaxonomyName

**Comment by patrickbrown-io** [comment]
Need to get all available taxonomies in the `fetchTaxonomy`--  where the code is failing is its failing to find a taxonomy with a valid ID the set of 50 if more than 50 terms exist. Will need to chain recusive fetch calls and aggregate terms similar to getting People.
