### ISSUE TITLE
Page title top and bottom padding is too big

### ISSUE THREAD

**Issue by nicolewaldrip** [CuBoulder/tiamat-theme#1067]
With the latest sandbox update, the default top and bottom padding for the page title is very large now and takes up more space on a page than it should. Please let me know if this was a specific request from someone on the UX team (or if this change was coming from some other request). 

Current padding (desktop view):
<img width="1381" alt="Screenshot 2024-06-13 at 1 18 27 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/159831859/257c693f-c2d4-4262-8bce-46214c01e3d2">

Current padding (mobile view):
<img width="373" alt="Screenshot 2024-06-13 at 1 18 36 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/159831859/4a0d95ec-a9a6-4aec-bd7b-1aff812a9add">

I would recommend we use padding for the page title that is more in line with how we have it set in D7 (let me know if you need me to pull specs for this):
D7 (desktop view):
<img width="1310" alt="Screenshot 2024-06-13 at 1 45 34 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/159831859/a70dda60-393e-4890-9214-6ef1e5b17105">

D7 (mobile view):
<img width="381" alt="Screenshot 2024-06-13 at 1 46 58 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/159831859/b4c72c8e-0eb0-48d7-9b81-4b45f9fff41f">

**Comment by jnicholCU** [comment]
I think this is due to having them in the edge-to-edge section.
The title shouldn't usually be in those but there is definitely a possibility right now so I'll go ahead and adjust to be the same as the contained sections.

**Comment by nicolewaldrip** [comment]
The top padding being too large is an issue regardless of what type of section it's placed in. Here is an example of it in its default location: https://live-ucbdev-sandbox-nicole.pantheonsite.io/page-title
Desktop:
<img width="1436" alt="Screenshot 2024-06-17 at 9 48 08 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/159831859/70b77723-7836-43d7-b217-5348a2ba2717">

Mobile:
<img width="374" alt="Screenshot 2024-06-17 at 9 48 18 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/159831859/a1c777d0-18bb-4371-bcc1-67ba94f83eb7">

**Comment by jnicholCU** [comment]
I will definitely see about tightening that up a bit better with my title changes today. 

I'm trying to keep the spacing consistent throughout all the blocks so with the title being a moveable block it can be difficult to make it look correct everywhere.

**Comment by nicolewaldrip** [comment]
Awesome, thank you! Not sure if it's worth noting or not, but it looks like on all of the test migrated sites that the updates got pushed to, the bottom padding on page titles is even more drastic (and those should all be placed in the standard area since you couldn't move page titles in D7). 

Here's an example of a migrated page with really significant padding: https://live-ucbprod-ecee.pantheonsite.io/research
<img width="1458" alt="Screenshot 2024-06-17 at 1 53 21 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/159831859/90b89dd6-14de-43cb-b66d-57ed6d82a9a9">

Here's the live D7 page: https://www.colorado.edu/ecee/research
<img width="1464" alt="Screenshot 2024-06-17 at 1 53 28 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/159831859/57c09374-2a7b-44ea-8efd-7012f6753d49">

**Comment by jnicholCU** [comment]
It looks like the title is getting thrown into its own section and column which each have its own padding so the padding isn't coming from the title itself but from the stacking of multiple sections in a row to create this effect. 
Going to talk about it with the team this morning.
