### ISSUE TITLE
Language block can't be removed if it's added to a page

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1076]
If someone adds the language block to a page in layout builder, it's not able to be removed: https://live-ucbdev-sandbox-emily-101.pantheonsite.io/block-types/compromiso-y-acciones-contra-el-racismo-del-crown-institute

**Comment by jcsparks** [comment]
what's a language block?

**Comment by patrickbrown-io** [comment]
Might be worth investigating, adds additional quality of life changes beyond what's expected to come in core:

https://www.drupal.org/project/layout_builder_browser
