### ISSUE TITLE
Form Submission AJAX 500 Error

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1086]
When trying to submit the Site Request Form (https://live-ucbdev-sandbox-webcentral-101.pantheonsite.io/request-website), I receive the following error:

Failed to load resource: the server responded with a status of 500 ()
AjaxError: 
An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /request-website?ajax_form=1
StatusText: error

I tried a form on one of our launched sites (https://www.colorado.edu/demos/webexpress/contact-us) and did not get this error.

**Comment by kevincrafts** [comment]
Also had the error on https://live-ucbdev-chancellor.pantheonsite.io/chancellor-engagement-request

**Comment by kevincrafts** [comment]
More info on this...

It looks like the submissions are being recorded, but emails are not being triggered/sent.

**Comment by jcsparks** [comment]
This may be an issue with SMTP not being fully setup to send...

**Comment by patrickbrown-io** [comment]
This appears to be resolved, likely when Devel Generate was disabled back in July. Closing for now
