### ISSUE TITLE
Web Manager can't see or access unpublished content from other users

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1097]
The Web Manager role is unable to see or access unpublished content from other users:

Web Manager view:
<img width="1495" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/600444b1-ee4d-4811-9f05-cd2df40046dd">

Developer View:
<img width="1415" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/7bd6079a-5804-416a-9089-fdc675dd4290">

**Comment by jcsparks** [comment]
Looks like the `Site Manager` role lost or never had the `Bypass content access control` permission that the other content creator roles have.  Should be an easy fix.
