### ISSUE TITLE
Print Stylesheets 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#1101]
Apparently the HLC Accreditation process needs to be able to print (likely to PDF) static copies of important webpages as part of that process.  

We'll need to create a set of print media stylesheets to make this process work a little better for them.  

Just looking for a first-pass, best-effort at this point as a starting place and will ticket out required enhancements going forwarded as needed.

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express_mono/blob/dev/themes/ucb/scss/ucb-print.scss

Points of interest

- Not all content of a page needs to be viewable on a printed version. We made the decision to hide a lot of elements that serve no purpose on a printed page, such as navigation, search, site wide regions (footer blocks), etc. Instead focused on content that was really unique to the page.
- Force expandables to expand so hidden content can be printed.
- Remove background images and replace with solid color.
