### ISSUE TITLE
People List errors if content included expandable shortcodes

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1117]
People list pages are not showing on Emily's sandbox site: 

https://live-ucbdev-sandbox-emily-101.pantheonsite.io/our-people
https://live-ucbdev-sandbox-emily-101.pantheonsite.io/test-people-list

When viewing these pages this error is generated:

Error: Call to undefined method DOMText::hasAttribute() in Drupal\ckeditor5_bootstrap_accordion\Plugin\Filter\BootstrapAccordion->process() (line 45 of /code/web/modules/contrib/ckeditor5_bootstrap_accordion/src/Plugin/Filter/BootstrapAccordion.php).

https://live-ucbdev-sandbox-emily-101.pantheonsite.io/admin/reports/dblog/event/31619

This is being caused by the expandable shortcode that is in the body field of a single person node: https://live-ucbdev-sandbox-emily-101.pantheonsite.io/caren-boulding

**Comment by timurtripp** [comment]
Fixed with an update to the [CKEditor 5 Bootstrap Accordion](https://www.drupal.org/project/ckeditor5_bootstrap_accordion) contrib module.
