### ISSUE TITLE
Changing focal point on image does not update images that are already in use

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1125]
If you change an image focal point after it has been added to a page through the media library into a WYSIWYG field, the image is never updated.

 Clearing the cache, resaving the page, or reinserting the image does not fix the issue.

Images that are used for thumbnails in content such as article lists and people lists do also not update unless the cache is cleared.

Images used in blocks such as content grids will update after the layout is resaved.

Images used in slider blocks do not require anything else to be done and will show the updated image automatically.

The large image in the screenshot below was inserted into the page and then the focal point changed to the top right corner (green square). The image is still showing the default position (center).

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/354258a1-190f-431e-8972-533dc40a0b5a">

Attaching a couple images I used for testing:

![color-grid](https://github.com/user-attachments/assets/d7a0a430-2f70-4865-b75a-d8a3a8933bb5)
![color-grid-2](https://github.com/user-attachments/assets/617d08bd-48f0-4973-84a5-f13b37e342e4)

**Comment by jnicholCU** [comment]
Updated with the pr for CuBoulder/tiamat10-profile#191
