### ISSUE TITLE
Newsletter Issues

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1133]
I saw the last ticket I created for newsletter issues was closed and merged over a week ago so decided I'd go and test.

**Missing Images**
There's multiple missing images throughout the email version of the newsletter
<img width="391" alt="image" src="https://github.com/user-attachments/assets/60a29865-d532-42fc-8639-be10d75bcf90">

Space between campus logo and newsletter title
<img width="616" alt="image" src="https://github.com/user-attachments/assets/151f0629-ceef-4700-8cff-74862f053d6b">

**Text size of newsletter title, date, view on website link**

D10 version
<img width="613" alt="image" src="https://github.com/user-attachments/assets/d7ac43fa-1975-4ea7-9b77-5b524c007c8c">

D7 version
<img width="675" alt="image" src="https://github.com/user-attachments/assets/3a19805f-8134-457f-8a98-7dd484c38ad7">

**Email**

When viewing the email using the code provided I came across these issues:

- all images are missing, including the campus logo
- the spacing and alignment of the newsletter title, date, and website link are off
- the website link color isn't correct
- The footer isn't readable because it's all white text on a white background

<img width="472" alt="image" src="https://github.com/user-attachments/assets/8edea65c-7d1b-4f95-b57d-3c80addeeed8">

**Comment by patrickbrown-io** [comment]
Breaking this into two tickets, using this one to handle the major bugs preventing testing.

Will continually update https://github.com/CuBoulder/tiamat-theme/issues/1150 with the minor style issues
