### ISSUE TITLE
Adding Images to Sliders

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1147]
One of the images in the slider at the bottom of https://www.colorado.edu/brand/ didn't make it over to D10 in the migration (https://live-ucbprod-brand.pantheonsite.io/) and I'm totally unable to add that image in the slider block in D10.

**Comment by jcsparks** [comment]
Hey @asvensen - this wasn't actually an issue with the slider.  It was a JS error with the shortcodes that was affecting the slider's ability to function correctly.  Now that the shortcodes module is turned off it seems to be working correctly for me now.  Feel free to close this issue assuming it's working for you as well.

**Comment by asvensen** [comment]
Hey @jcsparks. Thank you for the update. I'm still unable to add an image to the slider. There's a spot for it (as in the block is set to have 3 images, which is correct), but when I go to add the missing 3rd image, I'm unable to do so. (Error says "The maximum number of media items have been selected"). My guess I should just delete that 3rd slide and start over. I'll wait to hear back from you before I do that.

**Comment by jcsparks** [comment]
@asvensen  - yeah, I deleted the broken image reference and was able to add in a working third image.  Let me know if that doesn't work and I'll give you hand.

**Comment by asvensen** [comment]
Yeah, I still can't add it. Caching issue maybe?
