### ISSUE TITLE
https://live-ucbprod-brand.pantheonsite.io/how-use/be-boulder-messaging/tagline-modifier-lines

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1154]
I'm currently on https://live-ucbprod-brand.pantheonsite.io/how-use/be-boulder-messaging/tagline-modifier-lines in Chrome and when I try to click "Lockups" which is the next child page down from "Tagline with Modifier Lines" in the side navigation, nothing happens. It just drops me right back on the page I'm currently on. This is definitely a major blocker when it comes to replacing the D7 site with the D10 site. 

I also tried to navigate to it from the menu structure and that won't work either.

UPDATE:

It looks like this might be because "Lockups" goes to the first child below it, which is "Tagline and 1-Line Logo Lockup", which I can get to from the menu structure, but not navigating as a user would. I've manipulated this in the backend, but this is something migrating folks need to know can be an issue.

**Comment by asvensen** [comment]
I also tried to navigate to it from the menu structure and that won't work either.

**Comment by jcsparks** [comment]
![Screenshot 2024-07-29 at 5 18 45 PM](https://github.com/user-attachments/assets/7619a68c-8a10-43bd-8b43-cc1d8b4ab979)

You just need to check the `First child` box.  We only got a partial solution for the first child link issue in this migration.  We're hoping this will be a full solution for Cohort 1, but for now the links are created but you have to manually check the first child box on these type of links.

**Comment by asvensen** [comment]
Okay, thank you! Closing this now.
