### ISSUE TITLE
Migrated Site URLs

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1160]
On the migrated [Brand site](https://live-ucbprod-brand.pantheonsite.io/), if the link is not an old P1 link, a lot of them will be set to /brand/node/#, which just redirects that link to the homepage of the site. I believe the /brand shouldn't be a part of the link.

**Comment by jcsparks** [comment]
the p1 links will only be corrected via the AGCDN once the site is live.  This either needs to be manually corrected or wait for the site to go live and have the AGCDN rule attempt to rewrite it to the correct destination.
