### ISSUE TITLE
Hitting Enter in Font Awesome

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1162]
If you're using font awesome and hit the enter button when searching for an icon, you are exited out of whatever your doing, whether that be editing a page or a block and so you lose everything you were just working on. If this isn't a bug or something that can be fixed, perhaps this is something we can train on so people don't do it.

**Comment by timurtripp** [comment]
Hitting enter after typing a query into the icon picker search is completely unnecessary, the results come up automatically. But it would be a good idea to disable the enter key from doing anything while the field is focused so that people used to hitting enter for any type of search don't encounter weird behavior.

**Comment by asvensen** [comment]
Yeah, you're so right that it's unnecessary. It's more that it's habitual and keeps kicking me out of what I'm doing, which is frustrating when you're knees deep in a complex block and lose it all. I'm ALL for disabling that.

**Comment by timurtripp** [comment]
I found what's causing this and will make it so the enter button doesn't kick you off the page anymore. Thanks for letting me know!

**Comment by jnicholCU** [comment]
Tim's newest changes to the module handle the issues that Annie was running in to. 
Should be live in coming updates for all sandboxes.

**Comment by timurtripp** [comment]
Resolved with a commit to the [CKEditor 5 Icons](https://www.drupal.org/project/ckeditor5_icons) contrib module and will be in the next sandbox update.
