### ISSUE TITLE
Logging in issue

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#1166]
Every time I try to log in to the homepage site I get taken to this page: 
![Screenshot 2024-08-01 at 9 05 41 AM](https://github.com/user-attachments/assets/9a6ee6ac-c719-4bc5-b124-96bfa6d9b3b0)
I then browse back to the site and go to login and I'm already logged in. Just getting the page above immediately after the first login.

**Comment by jcsparks** [comment]
@wturnbull  - This is a problem with cookies getting too large for FedAuth.  If you delete your cookies for the site you're trying to log into and try it again it should work normally.  Seems to affect people who log into a lot of site more frequently.
