### ISSUE TITLE
Colorbox/Lightbox images inside the WYSIWYG editor

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1174]
D7 Express has image styles with Lightbox functionality: https://www.colorado.edu/demos/web-express/design-layout/image-sizes

Can these kinds of image styles be added to the WYSIWYG editor?

For existing sites that are using these, how will they be migrated?

**Comment by jnicholCU** [comment]
We should be able to use the same glightbox functionality from the image gallery for these.
The image style templates will need to be built out for them to work properly. 
Captions on images should be pulled in as well. I believe we do that with our image gallery.
