### ISSUE TITLE
.zip files on D10

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1177]
Working on the migrated Brand and Messaging site and checking all the forms. Users have the ability on the D7 site to download .zip files with assets. I can't upload those .zip files to D10 and so I can't sign off on several of the forms. Is it possible to make .zip a file extension that's allowable in D10?

**Comment by jcsparks** [comment]
Move the config for the document media to `config/optional` and we'll turn on the ability to add .zip files to the Brand site.

**Comment by asvensen** [comment]
I'm not sure how to move the config for the document media...

**Comment by jcsparks** [comment]
Sorry @asvensen - that message is for whichever developer picks up this ticket to work on.  That comment wasn't meant for you.

**Comment by jcsparks** [comment]
Closing this as they're going to move the zip files to a different service.
