### ISSUE TITLE
Basic Page - Social Media Icons Block

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#12]
Need to convert Social Media Icons Block Paragraph to Block that will work with Layout Builder.

**Comment by jcsparks** [comment]
Worked as a paragraph on the Basic Page in nextpress, but should grab the content from the Social Media Menu to be displayed in a block that can be placed with Layout Builder.

**Comment by TeddyBearX** [comment]
I believe the work on this stopped because of the `drupal_menu('social-media-menu')` function call not working. Custom links render fine though.

**Comment by TeddyBearX** [comment]
@jcsparks is it worth implementing this block if only the custom links work, and not the ones from the social media menu?

**Comment by jcsparks** [comment]
Shelve until 10.1 to see if re-usable blocks fixes this issue for us or at least gives a workaround.
