### ISSUE TITLE
People List Page Design

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#120]
There's a few issues with the design of the people list page:

- The list view should display their name, photo, job title(s), department, email, and phone number. and summary of their bio field.  The bio field on the person page should have a summary option they can use if they want to leave it blank.

![Screen Shot 2022-09-28 at 12 54 18 PM](https://user-images.githubusercontent.com/349713/192869787-5e8211c5-ee64-426c-b4e4-bd735a3208f1.png)

- People list page is missing options for user filtering
![image](https://user-images.githubusercontent.com/349713/192870144-91284e6e-7072-4544-8f10-77dad937fc09.png)

![image](https://user-images.githubusercontent.com/349713/192870319-a1dedb84-7cdf-4e9b-9165-771b1c1fe0e6.png)

I also noticed that the person content type is missing the 3 additional filter options that can be used to help group and filter people on a site.

**Comment by TeddyBearX** [comment]
Person page (tiamat-custom-entities):
- [ ] Add taxonomy terms for "Filter 1", "Filter 2", "Filter 3"
- [ ] Add fields for "Filter 1", "Filter 2", "Filter 3" under "Other" tab
People List Page page (tiamat-custom-entities):
- [ ] Add fields for filtering by "Filter 1", "Filter 2", "Filter 3"
- [ ] Add toggles for enabling filters to be user-accessible
- [ ] "Child Terms" option
People List Page (tiamat-theme):
- [ ] Refactor as web component
- [ ] The list view should display their name, photo, job title(s), department, email, and phone number. and summary of their bio field. The bio field on the person page should have a summary option they can use if they want to leave it blank.
- [ ] Build JavaScript and CSS UI for user-accessible filters
