### ISSUE TITLE
Sliders should advance automatically

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1202]
A slider block should advance automatically and pause if the mouse is hovered over the slider. Slides should pause for 7 seconds before advancing.

https://www.colorado.edu/demos/documentation/block-content/slider-block

**Comment by jcsparks** [comment]
We turned it off for a11y reasons... should probably have a discussion with the full group to ensure we're all on the same page about how this should work.

**Comment by kevincrafts** [comment]
Let's talk about it on Thursday.

**Comment by jcsparks** [comment]
Teams want it set to 7 seconds (or 7000ms for the devs)
