### ISSUE TITLE
Person page on smaller viewports

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1215]
While testing some content on a person page today I found if I viewed the page with the responsive preview or resized my browser window that it switched from the one column view back to a two column view at 575 pixels.

https://live-ucbdev-sandbox-kevin.pantheonsite.io/william-sanderson

<img width="687" alt="image" src="https://github.com/user-attachments/assets/9d1ebb60-7ba3-408d-8204-626b0e4f374b">

Responsive Preview: iPhone XS Max
<img width="568" alt="image" src="https://github.com/user-attachments/assets/610d3259-6754-4458-ace9-957c7c8fc508">

Responsive Preview: iPhone XS
<img width="524" alt="image" src="https://github.com/user-attachments/assets/6fe46a54-cc32-41b7-bc45-86b15def5ba5">

**Comment by jcsparks** [comment]
This doesn't feel right to me.  Going to run it by @kevincrafts to confirm how this is supposed to work and will get some clarity or merge this in, if this is what he wants.
