### ISSUE TITLE
Sliders set to large image sizes are displaying cropped images

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1234]
While most of the image styles used in the slider block will scale and crop the images, the large image style should only be scaling the image and not cropping them.

It looks like when a slider is set to use the large image style, it uses the focal_image_wide style instead, which crops the image to a 2:1 aspect ratio rather than keeping the original ratio.

The large image style on sliders should allow users to add multiple images of different aspect ratios and the slider should adjust as the slider advances.

Examples:
https://live-ucbdev-sandbox-kevin.pantheonsite.io/slider-test
https://www.colorado.edu/lab/barthelat/

Test Images:
![2400x1600](https://github.com/user-attachments/assets/b29c4695-b0d9-4b89-a403-76b5609abb72)
![2000x1500](https://github.com/user-attachments/assets/6878f614-61db-4d7c-a670-043acad323e8)
![3200x1800](https://github.com/user-attachments/assets/de790acc-561c-4491-b230-e1548b90373c)
![2400x1200](https://github.com/user-attachments/assets/06ac222e-1cd2-4a80-aba6-33a4029bee07)

**Comment by jnicholCU** [comment]
This was fixed in https://github.com/CuBoulder/tiamat-theme/pull/1252
