### ISSUE TITLE
Article Page Style - Zebra Style

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#124]
On the Zebra Striped mode : 

- colored section padding on the top/bottom should be increased from 0.5em to 2em
- The first and only the first section should not have expanding padding on the top 
- Hero sections should not have visible padding/color behind them at the top or bottom.

**Comment by TeddyBearX** [comment]
I had zebra striped looking better than this, wonder what happened. Will investigate.
