### ISSUE TITLE
Slider Ultra wide 1600:600 images are displaying as 1200x600

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1240]
Slider blocks set to display images using the ultra wide style (1600x600) are instead displaying their images at 1200 x 600 (2:1). This is causing two issues:

Migrated sites are displaying images cropped at a different size/ratio than intended. If a site had designed their images around that aspect ratio the images are being cropped.

The images are being scaled down, that may result in images being scaled up from their 1200x600 resolution.

https://www.colorado.edu/social-psychology/about-us

Related #1234

**Comment by jnicholCU** [comment]
This is going to need some changes to the image styles being used for the slider. I'm going to make them and edit the templates as needed. Shouldn't be any migration implications.
