### ISSUE TITLE
Video Reveal Size

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1286]
The initial size of the video reveal block (static image, text, play icon) should be 80 pixels of padding around the play icon and the text.

D7 example: https://www.colorado.edu/demos/web-express/add-bundles/video-reveal-block

But on https://live-ucbprod-center-mortenson.pantheonsite.io/green-infrastructure-water-quality-management-colorado the size seems to be a full screen.

**Comment by jacob-korf** [comment]
Closed with the resolution of the video reveal height solution #1294
