### ISSUE TITLE
No space between first and last name

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1304]
When viewing a person page on Chrome, there is no space between the first and last name.

https://www.colorado.edu/alc/katherine-alexander

<img width="657" alt="image" src="https://github.com/user-attachments/assets/ea7c2ff2-3194-47ee-8548-3c2b92c41630">

**Comment by timurtripp** [comment]
Saw this problem on the Anthropology site before one of the fixes that @AlanBCole ran that day. Not sure what's causing it on certain sites. Need to look into it.

**Comment by timurtripp** [comment]
It's actually still a problem on the Anthropology site, I thought I remember it being fixed. Hmm
