### ISSUE TITLE
HTML Email - version 20240918

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1311]
This is from a recent test of what I believe is version 20240918... viewed in Outlook

<img width="923" alt="image" src="https://github.com/user-attachments/assets/d21261f3-f820-4fce-940c-e9177ebba0b9">

1. Campus logo too small
2. Website link wrong color
3. Newsletter title too small, and date and website link should be smaller
4. Email header too large

Please look at the 9/17 SRS Insights email for examples on how this should be sized.

<img width="717" alt="image" src="https://github.com/user-attachments/assets/44b64eea-d4ab-4d4f-b674-a41fe8f2e1ab">

1. Spacing between border and next article is way too small. Spacing above and below the borders should be equal if possible.
2. Footer text is still invisible, depending on which theme the site is using for the newsletter. This screenshot is using the Classic theme.

https://live-ucbdev-sandbox-kevin.pantheonsite.io/newsletter/test-newsletter/test-newsletter

1. Content not aligned in gmail (minimal theme)

<img width="429" alt="image" src="https://github.com/user-attachments/assets/e90c2772-4cea-46df-b31f-287214afa425">

1. Classic theme in Gmail

**Comment by patrickbrown-io** [comment]
Will include https://github.com/CuBoulder/tiamat-theme/issues/1450
