### ISSUE TITLE
Remove mega menus from sticky menu

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1316]
If a site has the sticky menu enabled and has mega menus, those mega menus should not be toggled from the sticky menu.

https://live-ucbdev-sandbox-kevin.pantheonsite.io

<img width="1696" alt="image" src="https://github.com/user-attachments/assets/9a68482e-960a-4c36-9a57-d659b4fa27d0">

**Comment by jacob-korf** [comment]
Closed with PR #1327.
