### ISSUE TITLE
Clicking image preview in media library returns error

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1322]
Clicking the preview link on a media item gives an error - https://www.colorado.edu/initiative/applied-history/media/371/edit

AjaxError: 
An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /initiative/applied-history/admin/focal_point/preview/376/50x50?focal_point_token=BG7sZynCNkQ2A6zdR1uvWMjgw87t8M5GjVSoinXcaYY
StatusText: error
ResponseText: The website encountered an unexpected error. Try again later.

Looks like there's an associated php error:

Error: Call to a member function getDefinitions() on null in Drupal\focal_point\Controller\FocalPointPreviewController->getFocalPointImageStyles() (line 244 of /code/web/modules/contrib/focal_point/src/Controller/FocalPointPreviewController.php).

https://www.colorado.edu/initiative/applied-history/admin/reports/dblog/event/2013

**Comment by jnicholCU** [comment]
This is a known issue that has a patch working currently. Still has not been merged into the main branch though.
https://www.drupal.org/project/focal_point/issues/3462165

**Comment by jnicholCU** [comment]
This patch has been reviewed and looks to be ready to be merged in. Hopefully the issue will be resolved soon.

**Comment by jnicholCU** [comment]
Currently still being reviewed. It seems someone has more problems even with the patch.

**Comment by jnicholCU** [comment]
Issue is labeled as mergable, there still seems to be some question on if it's truly ready though as a couple users are having problems.

**Comment by patrickbrown-io** [comment]
This should be fixed now via https://www.drupal.org/project/focal_point/issues/3462165#comment-15859395
Seems to be working on test containers -- will be in the next update. Holding off on closing for now until after testing

**Comment by jnicholCU** [comment]
Nice!

**Comment by jnicholCU** [comment]
Looks like this is all working in the newest updates. Closing out the related tickets.
