### ISSUE TITLE
Content list thumbnails are too small

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1349]
The teaser view in a content list should match the teaser view of article and people lists, but it looks like these basic page thumbnails are too small:

<img width="961" alt="image" src="https://github.com/user-attachments/assets/9c070d9a-3b8e-4524-967f-a2788968f206">
https://www.colorado.edu/arotc/alumni/historical-photos-articles

Compared to the size of the article thumbnails on the news page:
<img width="1708" alt="image" src="https://github.com/user-attachments/assets/a37b4230-3106-4bc9-8f7b-c408afe04c0a">
https://www.colorado.edu/arotc/news-events/news

**Comment by jnicholCU** [comment]
@kevincrafts for the image styles were these specifications you gave us only for the sidebar? 
https://github.com/CuBoulder/tiamat-theme/issues/1169#issuecomment-2274245256
