### ISSUE TITLE
Getting an error upon trying to preview an article [severity:moderate]

### ISSUE THREAD

**Issue by timurtripp** [CuBoulder/tiamat-theme#1361]
```
Error: Call to a member function hasField() on null in boulder_base_preprocess_node__ucb_article() (line 291 of /app/web/themes/custom/boulder_base/boulder_base.theme).
```

I believe the error was introduced in PR CuBoulder/tiamat-theme#1312. Tagging @jnicholCU

**Comment by jnicholCU** [comment]
Yeah that's where that would be happening. Thought I had that case covered but I guess not. Will assign to myself and fix. Is this causing page break or just a error report?

**Comment by timurtripp** [comment]
Page break on the preview page, hence why I tagged it as moderate
