### ISSUE TITLE
Video Reveal and Video Hero override bug

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#1365]
The Video Hero Unit seems to be overriding the Video Reveal's functionality so they cannot be on the same page.  The hero unit's video will play but the video reveal won't work when clicking on the play button

This seems to have always been the case even before fixes for the GTM were implemented.

I spent some time trying different options like defering or async on the scripts but I haven't been able to figure out what is actually causing the problem. I think it has to do with the youtube iframe api being loaded twice via their respective .js files.

**Comment by timurtripp** [comment]
If the YouTube JS is one common library used by both blocks then this should get rid of the problem of it being attached twice.
