### ISSUE TITLE
Aggregator blocks have more padding than others and cause alignment problems

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1366]
Aggregator blocks don't align with other content due to additional padding:

<img width="1488" alt="image" src="https://github.com/user-attachments/assets/df578936-31a6-4199-a9bf-ebc1c8baf33f">

**Comment by timurtripp** [comment]
The RSS icon also uses Font Awesome 4 classes and needs to be updated.
