### ISSUE TITLE
People List Page Type + Last Name Sort

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1368]
It looks like there was an older ticket for this that was fixed (#280), but seeing this again on https://www.colorado.edu/center/oddace/core-team.

<img width="1378" alt="image" src="https://github.com/user-attachments/assets/18f9310d-c379-41dc-bc63-9c2df11ef9a0">

Director is set first, but she's showing up 5th in the list.

**Comment by timurtripp** [comment]
[developer note] Looks like the job type sort is hard-coded to be alphabetical and not based on the weight given to the taxonomy terms. This is a more specific issue than CuBoulder/tiamat-theme#280 but should be fixed.

**Comment by timurtripp** [comment]
Marking as [change] since this is a change of the current functionality.
