### ISSUE TITLE
Newsletter Archives & Lists

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1391]
In D7 Express, there's two ways to show previous newsletters:

Archive Page

A paginated list, sorted by most recent, of all newsletters of a specific type. This is not a content type. Just a path that will return the display of newsletters with the titles and summary.

Example: https://www.colorado.edu/today/newsletter/cbt-students

Newsletter List Block

A block can also be created that allows the editor to choose which type and how many (1-10) recent newsletters they want to display. Underneath the list there is a link to the archive page to see more newsletters. The display is the newsletter title and summary.

Example: https://www.colorado.edu/today/newsletter-list

**Comment by patrickbrown-io** [comment]
### Archive Page

There is an issue. The summary isn't simply a summary field on a Newsletter-- its a paragraph, in a paragraph, in a paragraph, which will have another reference to an Article if its one of those. Then the "summary" grabs the first Article or pseudo-Article title buried in the monster nesting dolls of paragraphs.  I don't believe we can dive that deep like that on a view which would satisfy the paginated and not a content type endpoint requirement.

Options:
- Content Type: we do it like the Issue Archive, js saves the day. We would need to manually add these pages. This could get messy.
- View without summary field, if summary isn't an option
