### ISSUE TITLE
Lightbox images require image captions

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1393]
The Lightbox images - where you click on a small image and a large image pops up - used to use the alt text as the description.  Now they require a caption, resulting in many images that require additional editing to get the description to be viewable again.

Is it possible to use the caption if there is one, and the alt text as a fallback if there isn't a caption?

**Comment by timurtripp** [comment]
@patrickbrown-io if you're handling this one, can you also look into CuBoulder/tiamat-theme#1379 (since both may be fixed in the same update)?
