### ISSUE TITLE
Articles by a person should be an optional configuration

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1398]
When a person has authored articles, they are automatically showing up on person pages.

This was intended as a way for a site to display this information if they chose, but now it's automatic and there doesn't seem to be a way to turn it off.

Daniel Leonard (https://www.colorado.edu/venturepartners/daniel-leonard), who manages the RIO site and is the author of a lot of their content, doesn't need (or want) an "Articles by Daniel" display on his page.

Can we add some configurations to this to give site managers more control of where this shows up?

**Comment by patrickbrown-io** [comment]
https://github.com/CuBoulder/tiamat-custom-entities/pull/186
https://github.com/CuBoulder/tiamat-theme/pull/1437

Will add in the per-node setting field on Person, which is defaulted to true. Can turn off the block using this field on specific pages. Will discuss to see if more settings will be needed.
