### ISSUE TITLE
Blocks placed in After Content, After Content 2, and Footer regions don't collapse to a smaller number of columns on mobile devices

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1407]
When multiple blocks are placed in the After Content, After Content 2, and Footer regions, the maintain a side-by-side display rather than collapsing to a few number of columns.

A site may add as many as 6 blocks in that region, which may be fine for large desktop viewing, but needs to shift to different numbers of columns based on the viewport width, and eventually collapse to a single column for a mobile phone viewer.

<img width="754" alt="image" src="https://github.com/user-attachments/assets/80e1f163-fea5-4441-9680-893b14cc51fd">

**Comment by jnicholCU** [comment]
Looks like this is a menu specific bug. 
Normal blocks stack and space properly in these regions.

**Comment by jnicholCU** [comment]
Scratch that. Top and bottom margin seems to be broken on other blocks in these regions again.

<img width="1365" alt="image" src="https://github.com/user-attachments/assets/3bba68c3-51f2-4fd6-9760-082a3aa10074">
