### ISSUE TITLE
Floated images aren't getting cleared properly

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1420]
If an article has a floated image and there's not enough text content to match, the float doesn't get cleared properly and causes other content below the main content region to also flow around the image.

For example, in the image below, the content in the red dotted border is part of the After Content 2 region, yet it is being placed next to the image that is part of the content region:

<img width="1326" alt="image" src="https://github.com/user-attachments/assets/390c66cc-eac7-4c7e-b68e-b883d0541ef8">

I'm unsure if this happens on other content types, but this behavior should not happen on any.

**Comment by timurtripp** [comment]
Could I get a link to the page with this problem? Including links makes figuring things like this out much easier.

**Comment by jcsparks** [comment]
https://live-ucbdev-sandbox-kevin.pantheonsite.io/2024/10/21/article-right-aligned-image

**Comment by timurtripp** [comment]
Looks like just needs a `clear: both;` that's an easy fix.
