### ISSUE TITLE
Article list based on taxonomy terms shows author date even though hiding it on articles

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#1429]
The Article List page generated for taxonomy terms shows the article authoring dates for each article, even though the Date/Time/Formatting was set to Hide Date/Time for each article. 

D7 taxonomy article page: https://www.colorado.edu/transfer-admissions
<img width="1472" alt="Screenshot 2024-10-23 at 11 16 33 AM" src="https://github.com/user-attachments/assets/c618d057-0638-4205-9cf6-a8c7c89012db">

D10 taxonomy article page: https://live-ucbdev-homepage.pantheonsite.io/admissions/transfer-admissions
![Screenshot 2024-10-23 at 11 17 19 AM](https://github.com/user-attachments/assets/70800532-affd-4f37-bb6b-1781a01ee9b0)

**Comment by jcsparks** [comment]
The taxonomy term pages are views in Drupal rather than Article List nodes, I think we can make this work because they're still templated, but I guess we're curious if this should work this same way for the other Article List nodes.

**Comment by jcsparks** [comment]
Honoring the date display per article is possible but could lead to a very disjointed looking list.  Want to confirm the rules around how this should be displayed and prioritized.
