### ISSUE TITLE
Floated embedded videos don't have any spacing around them.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1433]
If you add a video to a WYSIWYG field and float it, there's no spacing between the video and the text around it. Can we add the same margins that floated images have?

<img width="782" alt="image" src="https://github.com/user-attachments/assets/9dea5164-1eda-4f60-ba68-268438abc0a9">

Example: https://live-ucbprod-psych-neuro.pantheonsite.io/undergraduate-information

This isn't great on a mobile device though, because it makes the video pretty small - can we limit the floating of videos to desktop/tablet?

**Comment by patrickbrown-io** [comment]
Spoke with Kevin about Centered VIdeo as well. At mobile screen sizes, these will be un-centered (pillarbox spacing removed) and span full-width like the floated ones will do.
