### ISSUE TITLE
Homepage Theme Changes

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1435]
The homepage site, being the campus homepage, has a few display differences.

**Site Branding/Site Name**

The homepage site doesn't display the site name, and instead uses a larger display of the campus logo:
<img width="1584" alt="image" src="https://github.com/user-attachments/assets/f0a275f9-6ba5-485e-a128-eff22109a892">

**Site Footer**

Instead of showing the site name/contact info on the left and the Be Boulder/copyright on the right, the display is centered:

<img width="1570" alt="image" src="https://github.com/user-attachments/assets/57fcef11-857f-4673-969c-8f1556687694">

The current homepage footer includes:
Be Boulder
social links block
text block with site, copyright, and various links.

**Page title tag**

On other sites we automatically include "University of Colorado Boulder" at the end of the title tag, after the page title and site name. 

For this site it should only be the page title | University of Colorado Boulder

**Comment by jnicholCU** [comment]
We have some options carved out in the Advanced section of the theme's site settings to handle items like this but nothing that affects these specific needs. These requests will need added to those options.

**Comment by jnicholCU** [comment]
We need to add drop downs for region colors.
