### ISSUE TITLE
Need help with QA on homepage webforms

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#1440]
I'm rebuilding a few forms for the homepage, and need someone with more expertise on forms than me or Annie have (I'm not certain I've done the new forms correctly and want to make sure I don't miss anything). Joshua suggested I submit a ticket for this. I have tasks in Asana that I can assign to whoever can help out. There are about 5 forms and I have 1 or 2 left to build. Thank you for anyone who can help out!

**Comment by patrickbrown-io** [comment]
### Issues Identified:

- [ ] https://live-ucbdev-homepage.pantheonsite.io/bb/bus-lit , Fix issue with 66/33 form block which presents a skinny block. Due to the `col-sm-8` class on the block
