### ISSUE TITLE
URL issues when allowing D10 to generate a URL alias

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1443]
In order to get around the breadcrumb issue, I started going into the Brand site and checking "Generate automatic URL alias" and now I'm getting odd URLs like https://www.colorado.edu/brand/node/252/cu-boulder-logo. How do I fix this?

**Comment by jcsparks** [comment]
@jnicholCU - can you reach out to Annie to set up a meeting to walk through getting this working they way she wants?

**Comment by jnicholCU** [comment]
Closing this as it needed manual intervention and remaking of pages.
