### ISSUE TITLE
Site editors need to be able to clear floated content

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1451]
We had an issue about this before, but it was closed as "not needed".  I've been getting support requests of how best to manage and content when there are either floated images or boxes in the content.

In D7 there was a shortcode to clear floats, but in D10, can we add a WYSIWYG style that can be applied to elements that can clear floats?

Example:

https://live-ucbdev-sandbox-kevin.pantheonsite.io/floats
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/f8d1d95b-5a02-4227-9b3e-7b04ab62b4d1">

How I'd like it to work:
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/8eaa895b-6300-4e53-9747-a11b99c3a8f2">

**Comment by timurtripp** [comment]
Duplicate issue: CuBoulder/tiamat-theme#255
