### ISSUE TITLE
Article publish dates set to hidden still display on other view modes

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1465]
Even when a site sets the article date to hidden, it still shows up on other displays, such as article list pages:

<img width="918" alt="image" src="https://github.com/user-attachments/assets/d8690d49-8887-4f0d-bf49-aad38c3ca6c9">
https://www.colorado.edu/program/hydrosciences/symposium/all-abstracts

If the date is set to be hidden, either site wide or an individual article, it should not show on any other displays.

**Comment by patrickbrown-io** [comment]
Marking as duplicate : https://github.com/CuBoulder/tiamat-theme/issues/1429

We'll need to adjust all the aggregator blocks and the view.
