### ISSUE TITLE
Basic pages need an image field for sharing on social apps

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#149]
When basic pages are shared on other apps, such as Twitter, Facebook, Teams, etc, they should be displayed as summary cards and need a way to include an image when shared.  Depending where the content is shared, different meta tags are used.

**Comment by jcsparks** [comment]
This is hard to do in the theme because we don't have access to the meta tag at the time we're rendering the entities.  @jacob-korf is going to look for a contrib module that has this functionality.
