### ISSUE TITLE
Invitiation to users error

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#1494]
I tried inviting the admissions team as content editors on the new homepage site. I comma separated the list of users using only their identikey (no @colorado.edu) and received this: 

![Screenshot 2024-11-20 at 2 23 34 PM](https://github.com/user-attachments/assets/6783921d-c963-4d6f-aa45-a191debd3d87)

**Comment by jcsparks** [comment]
Sorry @wturnbull - this site had a bit of unique lifecycle and it looks like the SMTP password wasn't added to it.  I've put that in now and tested sending email.  Should work going forward.
