### ISSUE TITLE
Padding in layout sections

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#150]
Editors need the ability to specify the padding in a layout section in order to control how much of a background image is displayed and to control where the content is placed over the background image.

Top, right, bottom and left padding settings are ideal as the photo may have its main focus in any area.

Adding discrete padding settings for desktop, tablet, and phone breakpoints is also needed in order to adapt to the different screen sizes.  For example, adding in a 50% right padding on a background may be find for viewing on a desktop, but is not sufficient for a phone.

Values should allow pixels and percentages.

**Comment by jnicholCU** [comment]
Closed out in the UCB Bootstrap Layouts PR: https://github.com/CuBoulder/ucb_bootstrap_layouts/pull/8
