### ISSUE TITLE
Content row block has inconsistent image sizes

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1503]
The content row block on this page (https://www.colorado.edu/initiative/cubit/education-workforce-training/undergraduate-student-resources), set to large teaser, is showing inconsistent image sizes.

The large teaser, and large teaser alternate, should use images that are a 2:1 aspect ratio, but here is showing some images that are square, and some that are 2:1.

<img width="752" alt="image" src="https://github.com/user-attachments/assets/b35c9aec-3642-4cd7-9a31-ba390ab5243a">

**Comment by kevincrafts** [comment]
adding another example with a content grid block: https://www.colorado.edu/commencement/

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/6c03f9a2-3ab6-4026-a0a9-4eced3fbcbff">

**Comment by jnicholCU** [comment]
Okay a couple issues we have: 
The content row is using the same focal style as the grid so the image sizes were recently changed from 2:1 to 3:2 which is causing the sizing change. 
For some reason focal point didn't update all the images with these specifications which is really weird as it has done it every time before. 
I'm going to be making a new focal style for the content rows that are 2:1 while keeping the old focal wide for the content grids at 3:2.

I'll need to see how to regenerate these images though if focal point isn't going to do it automatically like it has before.

**Comment by jnicholCU** [comment]
The first article in Article teasers will need to use the new 2:1 style as well so I'll update the templates accordingly for that. Will ping @patrickbrown-io if I have any concerns.

**Comment by jnicholCU** [comment]
Found a weird problem with the row template where the first two images are displaying with the square image style no matter what.

**Comment by jnicholCU** [comment]
Unlinked rows were displaying a different image style. Was a more simple fix than expected.

**Comment by jnicholCU** [comment]
There looks to be a problem with image style regeneration. Going to set up a second ticket for that and discuss with the team tomorrow. PRs for the teasers should be up soon.

**Comment by jnicholCU** [comment]
As of right now if you change the image and save the block + page. Then replace the image again with the one that is rendering improperly it should regenerate it's image style. It's a pain that it's not doing it automatically at the moment. Will look into why. Most likely guess is a bug was introduced into the focal point module.

**Comment by jnicholCU** [comment]
Link for the ticket regarding the style generation issue: #1524
