### ISSUE TITLE
Size of logo is different in different browsers

### ISSUE THREAD

**Issue by timurtripp** [CuBoulder/tiamat-theme#1505]
Safari:
<img width="1624" alt="Screenshot 2024-11-25 at 3 06 38 PM" src="https://github.com/user-attachments/assets/9296371f-1c0b-4d93-a7a6-e84bfc060a5f">
Firefox:
<img width="1624" alt="Screenshot 2024-11-25 at 3 06 49 PM" src="https://github.com/user-attachments/assets/0cc40541-7b9e-4b2e-80cb-7baee9f90249">

**Comment by jnicholCU** [comment]
This is a weird one. I didn't realize firefox had problems with applying width: 100% to SVGs. Classic.

**Comment by timurtripp** [comment]
Firefox's support for CSS in embedded SVGs is behind other browsers, that's something I noticed when I was developing our custom styles for CKEditor 5 Icons.

**Comment by timurtripp** [comment]
It may have actually been Safari, not Firefox...in any case there are differences with how browsers handle them.

**Comment by jnicholCU** [comment]
Safari looks correct. I'll see what I can do with the firefox view. Looks to be a pretty common question on stackoverflow so I'll just figure what works best for our use case.
