### ISSUE TITLE
Newsletter List block doesn't have a loading icon, and the archive link is a 404

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1506]
https://www.colorado.edu/today/faculty-staff-email-archive

There's no loading icon here like we see on other similar displaying (article & people lists) so it makes it seem like it's broken because it takes a very long time to load, or sometimes doesn't load at all.

Once they do load, the links to off to the homepage site, not /today, so they all results in 404s.

Also, the archive link at the bottom of the list links to a 404 - https://www.colorado.edu/today/newsletter/faculty-staff-edition

**Comment by patrickbrown-io** [comment]
@kevincrafts. For the 404 -- this will affect any taxonomy terms created before the Archive List Page was created. You must go into edit the terms you'd like an Archive for and check 'Generate Automatic Url Alias' for it to link to the Newsletter term archive page correctly

<img width="758" alt="Screenshot 2024-12-11 at 3 12 25 PM" src="https://github.com/user-attachments/assets/172ae887-d096-4c4c-84e5-7f32f98e4445" />
