### ISSUE TITLE
Newsletters are missing images

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1508]
<img width="683" alt="image" src="https://github.com/user-attachments/assets/e1f6ba90-28ab-460e-b6ed-2d03caa9ae3a">

https://www.colorado.edu/initiative/cubit/newsletter/newsletter/november-2024

Looks like part of the path is being repeated: https://www.colorado.edu/initiative/cubit/initiative/cubit/sites/default/files/styles/focal_image_square/public/2024-11/flairtech.png?h=11b34633&amp;itok=7vw3g7jK

**Comment by patrickbrown-io** [comment]
For documentation: https://www.colorado.edu/initiative/cubit had issues but https://www.colorado.edu/developer-sandbox did not, and this has worked for all other sites. Modified how base url is constructed which should resolve the issue for this particular site but have no way of testing the change in a local container.
