### ISSUE TITLE
Sidebar Menu styling adjustments

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1513]
**Active menu item**

Highlight only the active menu item - when multiple menu items are highlighted with the same styling it can be distracting to where you are in the site:

D10
<img width="1210" alt="image" src="https://github.com/user-attachments/assets/eeb03004-0527-40c3-b6c3-a9d026183b1f">

D7:
<img width="1504" alt="image" src="https://github.com/user-attachments/assets/3bad2455-dd69-4ae0-9c53-4b970322cd29">

Sidebar Menu Color Options

Can we add a theme option for sidebar menu color? Keep the gold as the default, but add a gray option? #e0e0e0, or whatever the light gray color we're using is.

<img width="516" alt="image" src="https://github.com/user-attachments/assets/1137a665-58ef-4da3-a0d4-cfccb49201ac">

**Comment by jnicholCU** [comment]
Found a weird problem with the row template where the first two images are displaying as square no matter what.

**Comment by jnicholCU** [comment]
This is doable as a theme style option. Will add sidebar menu libraries to handle it appropriately.

**Comment by jnicholCU** [comment]
Resolved in https://github.com/CuBoulder/tiamat-theme/pull/1544
