### ISSUE TITLE
Newsletter teaser thumbnail too big

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1515]
The thumbnail image of teaser articles appears too large compared to the content next to it.

![IMG_D2EFC0753AF2-1](https://github.com/user-attachments/assets/6a51c074-43a6-4d06-af6f-6eac3b8771b4)

**Comment by jnicholCU** [comment]
Does this look right @patrickbrown-io 

![IMG_D36C613D733F-1](https://github.com/user-attachments/assets/1aa435de-0a07-456f-af37-8b46582c1a00)

**Comment by patrickbrown-io** [comment]
@jnicholCU Looks right to me, they're actually square. Thanks for testing!
