### ISSUE TITLE
Layout Builder Enhancement - Initial Workflow

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#160]
Generally speaking, content editors are going to want to add a "Custom Block" from a template when they click the "Add Block" button in the layout builder interface.  It would be nice if this was the default UI element that came up rather than having them click the "Add Block" button and then the "Create Custom Block" button to get there.  

Additionally it would be nice to customize the "Create Custom Block" interface to group similar content types and add other content types that aren't technically blocks from custom templates (e.g. the Today block) to this interface element.  

Not sure what's available for use to override and modify here but we should investigate to see if we can make the interface better for our users.

**Comment by jnicholCU** [comment]
As of now there is only 1 good workflow restrictor that works with the Gin lb. https://www.drupal.org/project/layout_builder_restrictions 
The layout builder workflow has a lot of push behind it for previous or new workflow interface so there is most likely going to be more work done.
At the very least if we want to restrict right away the layout builder restrictions module is useful.
