### ISSUE TITLE
RSS feed Block

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#169]
The RSS block shows the linked titles from an RSS feed. The number of items shown(1-10) can be chosen by the editor. Below the items, there is a link to feed.

Demo: https://www.colorado.edu/demos/web-express/add-bundles/rss-feed-block

**Comment by jcsparks** [comment]
Waiting for 9.5 and/or D10 as the RSS code is moving out of core and into a supported contrib module at that time.

**Comment by jnicholCU** [comment]
Aggregation module is now contrib: https://www.drupal.org/project/aggregator
