### ISSUE TITLE
Teaser content with out thumbnails

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#175]
When content is displayed as a teaser, it should not be indented if it does not have a thumbnail set.

![image](https://user-images.githubusercontent.com/349713/201761557-f52064b3-466e-498c-8662-eb086a02c48f.png)

https://live-ucbdev-sandbox-demo.pantheonsite.io/news-announcements

**Comment by TeddyBearX** [comment]
@jacob-korf _People List_ has a similar indentation issue, worth fixing it there as well.
