### ISSUE TITLE
Reusable Blocks for Layout Builder 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#19]
Need to see if this patch if far enough along that we can use it : https://www.drupal.org/project/drupal/issues/2999491

Otherwise we'll have to wait until it's part of core (hopefully 9.5 at the end of the year).

**Comment by jnicholCU** [comment]
Drupal Usability Meeting from 07/01/2022 apparently talks about this patch a bit, will watch to garner information.
https://www.youtube.com/watch?v=Q68C3GdRpZQ

**Comment by jnicholCU** [comment]
Duplicate Issue. Closing this one
