### ISSUE TITLE
Alumni Class Notes changes

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#206]
**Node title Display**
Node title should include title and class year, however we may want to make this a display option after testing this with the Coloradan site if it would cause issues with their existing content

**Add images to Alumni Class Notes content type**
An image field needs to be added to the Class Notes content type that will allow for multiple images.

**Image Display**
Display images as square thumbnails, vertically stacked, similar to the established teaser view modes.
Notes that do not have an image should be aligned to the left side to the element

**Mockup**
![class-notes-mockup2](https://user-images.githubusercontent.com/349713/215142451-8e2b8d3b-2115-4276-ad8e-a2ed2e8d6b2a.png)

**Comment by patrickbrown-io** [comment]
Just found this ticket deep in the backlog. Will amend https://github.com/CuBoulder/tiamat-theme/issues/622 and introduce these changes to the Class Notes List and Class Note pages. Right now the Note pages allow for one photo and do not display on the Notes List.
