### ISSUE TITLE
New Roles Needed

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#209]
- Architect - Role above Site Owner but not quite a full Developer.  Should include Configuration Manager, Layout Manager as well as User Management.  (this will be the role for Jo, Annie, Wendy and other IA support staff from SRC).  
- Configuration Manager - Add on role to give users ability to modify CU Site Settings normally reserved for Site Owners.  
- Layout Manager - Add on role to allow trusted users to edit Blocks and Block Layout 

Speaking of user management, we should evaluate : https://www.drupal.org/project/administerusersbyrole

This module looks to allow users hierarchically.  

Alternative or perhaps additionally this one : https://www.drupal.org/project/role_delegation

**Comment by kevincrafts** [comment]
Additional permissions for architect role:

- Administer affiliation (configure and display affiliation under site title)
- Administer Site Search (configure site to use search this site feature - requires previous work of setting up custom search)
- Administer Match Redirect
