### ISSUE TITLE
Person Name Fields

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#220]
Is it possible to remove the "Full Name" field and concatenate the first and last name fields rather than require each name to be entered twice?

In D7 there was a way to set the node title field's value programmatically with values from other fields and I wonder if the same can be done here.

![image](https://user-images.githubusercontent.com/349713/217664332-f3cab14e-26ae-4b36-b34a-f0fecc958612.png)

**Comment by jcsparks** [comment]
There's a known issue with form alter hooks and the focal point module.  We actually have a working module to fix this but because of the bug with focal point we can't turn it on yet.  

See : https://www.drupal.org/project/focal_point/issues/3307345

**Comment by patrickbrown-io** [comment]
Resolved in https://github.com/CuBoulder/ucb_person_title/pull/4
