### ISSUE TITLE
Blocks with the same title

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#226]
Blocks created on the Block Layout tool (admin/structure/block) require unique names for the titles, so does not allow for the possibility of having a different "latest news" or "upcoming events" blocks for different pages.

![image](https://user-images.githubusercontent.com/349713/217670503-f8972638-b9f1-4e54-9838-b23ac11ad2c1.png)

**Comment by jcsparks** [comment]
Looks like this will be fixed in Drupal 10.1 - https://www.drupal.org/project/drupal/issues/3272969
