### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#227]
Express should have short, medium, and long date formats that are used for various types of content.

Dates, such as the publication date of an article, should use these formats but should not be user selectable as we want the formats to be consistent across the entire platform.

Formats for D7 Express are defined here: https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_date_formats/cu_date_formats.module

**Comment by TeddyBearX** [comment]
We've implemented this in CU Boulder Site Configuration → Appearance.
<img width="336" alt="Screen Shot 2023-05-18 at 10 55 15 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/22628823/1f30fd52-e1b5-436f-afda-4c3fb3bfcd09">
