### ISSUE TITLE
Hide theme options

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#231]
There are some theme options that are not meant to be accessed by site editors and these should be hidden from the form:

Page Element Display
Logo Image
Favicon

![image](https://user-images.githubusercontent.com/349713/217672770-47443d03-60af-48a4-9cce-cab9ba6cb6a2.png)

**Comment by TeddyBearX** [comment]
We plan to restrict the theme settings by having only `/admin/config/cu-boulder/appearance` available to some users, the default theme settings page at` /admin/appearance/settings` should not be accessible at all.

**Comment by TeddyBearX** [comment]
<img width="1110" alt="Screen Shot 2023-02-09 at 9 58 35 AM" src="https://user-images.githubusercontent.com/22628823/217884469-12889e88-b859-4f6c-a338-f91a47a003b5.png">
