### ISSUE TITLE
Campus News Block

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#232]
The campus news block allows other web express sites to display content from CU Boulder Today.  The CUBT site has some endpoints that provide various vocabulary options for site editors to choose which articles from CUBT will show up on their site.

For example, https://www.colorado.edu/today/syndicate/article/options/category provides a list of categories for site editors to choose from.

The base endpoint for articles is https://www.colorado.edu/today/syndicate/article, but various options can be passed to this url to return different results - you can see the code for building that query starting at https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_campus_news_bundle/cu_campus_news/cu_campus_news.module#L225

The display of the CUBT content should match the options for the Article List, Article Grid, and Article Feature blocks. You can see options of this on https://www.colorado.edu (the CU Boulder Today News section), https://www.colorado.edu/students (CU Boulder Today Student Edition), https://www.colorado.edu/faculty-0 & https://www.colorado.edu/staff (CU Boulder Today)

**Comment by TeddyBearX** [comment]
We also know the block isn't ideally placed with our other blocks in Layout Builder, this is something we'd like to work on. But regardless, it is there!

**Comment by TeddyBearX** [comment]
<img width="453" alt="Screen Shot 2023-02-09 at 10 57 12 AM" src="https://user-images.githubusercontent.com/22628823/217898096-47c85e11-f3e0-4551-930e-8bfd5b00b767.png">

**Comment by kevincrafts** [comment]
This doesn't show up on my sandbox site, sorry if I'm creating duplicate issues.

**Comment by TeddyBearX** [comment]
@kevincrafts The workflow for adding this block isn't to click "Create custom block", not sure if that helps at all

**Comment by jcsparks** [comment]
The workflow for the campus news block is different which is a separate issue but we're going to wait for D10's version of the Layout Builder to shake out a bit before we try to override how it works.
