### ISSUE TITLE
Article Teaser Display

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#237]
**Date Format**
Date format should be:
Feb. 14, 2023

**Summary**
If summary is using trimmed content, an ellipsis should be added to the end:
![image](https://user-images.githubusercontent.com/349713/218887389-3a3ed6ca-6993-414c-a0e9-6c03d041fde4.png)
If the summary field is used, there is no need for an ellipsis.

**Border**
Borders should be a single pixel width

Alignment
Text, thumbnail, and borders should all be aligned
![image](https://user-images.githubusercontent.com/349713/218887706-a888efd3-c2ab-4d7a-a8ca-78b0fedc0c79.png)

**Comment by TeddyBearX** [comment]
Alignment fixed via #363
