### ISSUE TITLE
Add Source View/Edit to WYSIWYG Editor

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#242]
Sometimes a user may copy and paste some content that might need to be edited in an HTML view to fix.

**Comment by jcsparks** [comment]
I don't see a view source option in the D7 Express, though maybe I'm missing it -- there are a lot of buttons.  Normally viewing raw HTML is something that we only allow in the Full HTML mode, not it WYSIWYG.
