### ISSUE TITLE
Related Articles

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#246]
Can we move the configuration and display options of this to be more of a global setting? Having to manually configure all of your articles with identical settings is adding a lot of work for site editors. We shouldn't expect a site with hundreds or thousands of articles to configure this on each node.

Moving this to a block that could then be added would keep the configuration in a single place while allowing site editors a way to add it to sets of articles if they choose in a single step rather than doing it on each one.

**Comment by TeddyBearX** [comment]
Sister issue opened in CuBoulder/ucb_site_configuration#22, once that is completed further work should be tagged with this issue.
