### ISSUE TITLE
CKEditor 5 Plugin: Close Margin

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#252]
There's still a number of shortcodes from Drupal 7 Express that need to be implemented. Below are the remaining shortcodes and descriptions of how they work. Most shortcodes, unless specified, come from the cu_shortcodes module: https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_shortcodes

Close Margin
Removes bottom margin to reduce space between elements
[close-margin /]

**Comment by jcsparks** [comment]
No longer required.  Closing.
