### ISSUE TITLE
CKEditor 5 Plugin: Clear

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#255]
There's still a number of shortcodes from Drupal 7 Express that need to be implemented. Below are the remaining shortcodes and descriptions of how they work. Most shortcodes, unless specified, come from the cu_shortcodes module: https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_shortcodes

Clear
Clears any floats that may have been added.
[clear/]

**Comment by jcsparks** [comment]
No longer required.   Closing.

**Comment by timurtripp** [comment]
Resolved via CuBoulder/tiamat10-profile#226
