### ISSUE TITLE
CKEditor 5 Plugin: Print

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#259]
There's still a number of shortcodes from Drupal 7 Express that need to be implemented. Below are the remaining shortcodes and descriptions of how they work. Most shortcodes, unless specified, come from the cu_shortcodes module: https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_shortcodes

Print
Adds a "print this page" link.
[print]Print this page[/print]

**Comment by jcsparks** [comment]
No longer required.  Closing.
