### ISSUE TITLE
CKEditor 5 Plugin: Sidebar

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#261]
There's still a number of shortcodes from Drupal 7 Express that need to be implemented. Below are the remaining shortcodes and descriptions of how they work. Most shortcodes, unless specified, come from the cu_shortcodes module: https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_shortcodes

Sidebar
Provides a floated element with optional styles and float direction.
[sidebar float=right/left style=plain,border]Here is some text for a sidebar callout[/sidebar]

**Comment by TeddyBearX** [comment]
Once `box` is done this will be relatively easy with mostly reused code from `box`.

**Comment by TeddyBearX** [comment]
I don't see any information about sidebar on [the Shortcodes documentation page](https://www.colorado.edu/demos/web-express/web-express-core/content-styling/shortcodes). I'm also struggling to see why someone can't just use a box for this and it needs its own dedicated plugin.

**Comment by jnicholCU** [comment]
Will bring up with Kevin and see if he can give us any input. Strange it's not in that documentation. I wonder if it's even being used anywhere. I'll let you know once I've got some info back.
