### ISSUE TITLE
Enabling New Functionality

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#263]
Web Express has a lot of functionality that not every site needs. In order to make the interface cleaner and less confusing, D7 Express uses a custom module to allow site owners to enable a set of specific modules on their sites - the Bundle modules.  Each bundle module has its own set of permissions and dependencies for enabling additional modules.  These bundle modules can contain anything from configuration settings (SEO Bundle), to new content types (Article Bundle), or new block types (Localist Bundle).

The idea that we had here, instead of creating a custom module to handle this, was to have all bundles enabled, but add groups of permissions as needed to expand the functionality available.

My concern here is that there aren't specific permissions for block types, so each site will have all blocks available, even if they don't have the other required elements. For example:

- Article list blocks, but no way to create articles
- People List Blocks, but not way to create people
- Collection Grid Block, but not way to create collection items

This can create a confusing experience as exposing a subset of site building tools that don't work without other tools. The result of this is:

- making the site appear broken, since it might contain a block, but a user can't find the related content type
- make the site actually broken, should a user create a block for a content type that doesn't exist
- make the site more complicated to use since there are many more options available for block content

Looking through our current bundles (26 total) at least 14 of them include at least one block, so there are a significant amount here that will be exposed on a site with a default installation.

**Comment by jcsparks** [comment]
Spoke at length with Kevin and the rest of the UI/UX team.  We're going to focus on a role-based implementation for access control to functionality going forward.  Block-level permissions were added in Drupal 10.1.
