### ISSUE TITLE
Custom Logo/Site Name

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#264]
Some sites have been given an exception to branding guidelines and are allowed to have a custom mark in place of their site name.  Three of these sites are on the Web Express platform.  Sites need to have the ability to add 2 logos - one for light backgrounds, one for dark backgrounds so the appropriate logo will display with whatever site name background color they have picked.  

Images should be displayed at 1/2 size in order to appear sharp on retina devices.  For example, if a 1000px wide logo is added, that image should be scaled in the browser down to 500px.  Images must also still scale for tablet and mobile devices.

Only Architects and Developers should have permission to add these.

Examples:
https://www.colorado.edu/fiske/
https://www.colorado.edu/business/
https://www.colorado.edu/law/

**Comment by TeddyBearX** [comment]
**Project outline**

- Create an "Advanced" section of CU Boulder site settings → Appearance that requires a special permission to view
- Assign this permission to the "Architect" and "Developer" roles
- Move all the restricted theme settings to this region
- Add two new theme settings and file uploads to this section, one for light and one for dark logo:
  - I'll have to investigate how to handle these file uploads

**Ramifications**

This will change how Site Configuration handles the accessibility of theme settings. Users with the "Architect" role will gain access to "Where to display the Be Boulder slogan on the site", "Display the standard Boulder secondary menu in the header navigation region", "Display the standard Boulder menus in the footer region" under the "Advanced" section in CU Boulder site settings → Appearance but users with "Site editor" or "Site owner" will remain unable to see this section.
