### ISSUE TITLE
WYSIWYG fields do not allow line breaks.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#276]
Pressing enter in a WYSIWYG field should start a new paragraph, but pressing shift+enter should make a line break.

**Comment by jcsparks** [comment]
@kevincrafts  this seems to be working properly for us in testing, can you point us at a specific place where it isn't working this way?

**Comment by kevincrafts** [comment]
When pressing shift+enter on my test site it creates a new paragraph instead of inserting a line break - https://live-ucbdev-sandbox-kevin.pantheonsite.io/line-break-test
