### ISSUE TITLE
Footer Regions

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#283]
Footer regions should be a single region. Current Express has a theme setting to set the number of columns, but now I think this can just auto set the blocks placed here to all be equal width instead with flexbox. 

![image](https://user-images.githubusercontent.com/349713/225156054-d90fa844-8ad7-441c-8bfa-8c8a8ce7a124.png)

**Comment by jcsparks** [comment]
Merged in a update to resolve this.
