### ISSUE TITLE
Theme Regions

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#284]
In order to have block content move to the right areas on migration, the new theme needs to have similar regions set up. Users will expect their content to display in the same locations:

![Screen Shot 2023-03-14 at 5 02 18 PM](https://user-images.githubusercontent.com/349713/225161291-6e531190-eef0-447c-bd3f-11ec2f47057c.png)

As referenced in #283, block width can just be set on the number of blocks added to those regions so they are all the same width, however, breakpoints need to be set for tablet and mobile. For example, if 4 blocks are added to the footer region, the resulting width of each block should be 25% (4 columns), on a tablet that can be changed to 50% (2 columns), and on mobile 100% (single column)

**Comment by jcsparks** [comment]
Merged in an update to resolve this.
