### ISSUE TITLE
Images in Content Grid Blocks

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#298]
The content grid block has a setting to either display the images as square or wide, but when an image is placed they display in a tall aspect ratio and get cropped differently.

Examples below:
![Screen Shot 2023-04-03 at 1 25 18 PM](https://user-images.githubusercontent.com/349713/229607762-69be93c7-a7bd-4425-b3b9-4757c3e64f5d.png)
![Screen Shot 2023-04-03 at 1 24 48 PM](https://user-images.githubusercontent.com/349713/229607767-42de34f0-a581-4588-a2e9-e6283868e16a.png)

**Comment by jnicholCU** [comment]
This is a block layout issue vs a layout builder issue. Needing to refactor the blocks & layout builder css to accommodate for both use cases now.
