### ISSUE TITLE
Placing a block in a region loses the region that was chosen

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#302]
When placing a block via the Block Layout screen, the user is given a "place block" button in each region.

![image](https://user-images.githubusercontent.com/349713/229615284-8fc15f18-a03a-4ac4-b9d0-b6f745e5b3c0.png)

However, once you create the block, you are set back to a screen where the region is not set:

![image](https://user-images.githubusercontent.com/349713/229615522-412d5e76-6f42-47fe-a179-8dab89a3ae57.png)

**Comment by jcsparks** [comment]
This is core Drupal functionality that we're not going to change.
