### ISSUE TITLE
Adding images in Layout Builder Broke

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#307]
Not sure when this happened or how but new images can no longer be added to the media library when creating blocks in the Layout Builder

<img width="1233" alt="Screenshot 2023-04-06 at 11 13 08 AM" src="https://user-images.githubusercontent.com/94021017/230449113-d014f0c9-a50f-4d3c-b2c9-4493c15a3c7a.png">

The display should show like this

<img width="810" alt="image" src="https://user-images.githubusercontent.com/94021017/230449228-9e78a069-a988-4317-8a88-eaeb0d9bbe25.png">

**Comment by jnicholCU** [comment]
I believe this tied to the Gin LB Module
When removed the upload works as intended

**Comment by jnicholCU** [comment]
Turns out there is a ticket of this issue on D.O
https://www.drupal.org/project/gin_lb/issues/3349745

**Comment by TeddyBearX** [comment]
I was wondering what was going on here...thanks for getting to the bottom of it!
