### ISSUE TITLE
Field descriptions for Person content type

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#308]
Type:
Used to group people into categories such as administration, faculty, staff, etc.

Phone:
Include the area code and use the following format: 303-555-1212

Links:
Is there a way to remove the default text "Start typing the title of a piece of content to select it. You can also enter an internal path such as /node/add or an external URL such as http://example.com. Enter <front> to link to the front page. Enter <nolink> to display link text only. Enter <button> to display keyboard-accessible link text only."? The examples of linking to a node/add page or using those tokens we think will be confusing to our users.

**Comment by TeddyBearX** [comment]
_Job Type_ and _Phone_ descriptions completed in CuBoulder/tiamat-custom-entities#48
