### ISSUE TITLE
Custom Entities and Profile configuration files cleanup

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#323]
At some point we merged duplicate files into both the custom-entities config folder and profiles config folder

Previously the profile would handle everything to do with the media library and image styles
`image.style` files, aside from the defaults, should also live in the `optional' folder of the profile

These files also ended up in the custom-custom entities folder. Before when I had accidentally done this the files would cause the `install-site` command to fail and throw errors because of duplicates. This is not the case anymore apparently. Will need to look into why. Either way it's probably dangerous to have duplicates of these files.

**Comment by TeddyBearX** [comment]
These dupes were just merged in with the image styles work, I don't recall seeing any previously.

**Comment by TeddyBearX** [comment]
Custom entities doesn't throw any errors when installed with existing config, it simply overrides the existing config. Disabling and reinstalling the module has been my primary way of applying updates to my existing local development site.

**Comment by jnicholCU** [comment]
> These dupes were just merged in with the image styles work, I don't recall seeing any previously.

I double checked before I did the merge to see if they were already in there. If they weren't I was going to have Jacob clean up his PR beforehand. As it is the files were already in both places.

**Comment by TeddyBearX** [comment]
> > These dupes were just merged in with the image styles work, I don't recall seeing any previously.
> 
> I double checked before I did the merge to see if they were already in there. If they weren't I was going to have Jacob clean up his PR beforehand. As it is the files were already in both places.

I'm fairly certain they were added during the meeting where he and I were troubleshooting install issues. It did fix the install problem, somehow...but I think what we were both missing was the `optional` folder.

**Comment by jnicholCU** [comment]
> > > These dupes were just merged in with the image styles work, I don't recall seeing any previously.
> > 
> > 
> > I double checked before I did the merge to see if they were already in there. If they weren't I was going to have Jacob clean up his PR beforehand. As it is the files were already in both places.
> 
> I'm fairly certain they were added during the meeting where he and I were troubleshooting install issues. It did fix the install problem, somehow...but I think what we were both missing was the `optional` folder.

Ah okay, I'll go through the files and see what does and doesn't cause issues. I have a feeling some things changed from how they were before we moved to the newer tiamat-theme.
In the previous theme we had to worry about different duplicates differently because of our settings to have custom-entities and paragraphs as separate Features to export and install.
