### ISSUE TITLE
Refactor Roles and Permissions

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#329]
Roles : 
- Developer (most privileged role - used by development and operations team)
- Architect  (next most privileged role - used by UI/UX team) 
- Site Owner (tagging only, no permissions conferred) 
- Site Manager (create, edit and delete node content.  add users and update site configuration) 
- Content Editor (create, edit and delete node content)
- Edit My Own Content (can edit content they own but not content created by others)
- Layout Manager (access to blocks and block layout) 
- Newsletter (access to the newsletter node type)
- Webform Editor (access to create, edit and delete webforms) 
- Submissions Viewer (access to view submissions to webforms)

**Comment by TeddyBearX** [comment]
Site Owner (site_owner) → Site Manager (site_manager)
Site Editor (site_editor) → Content Editor (content_editor)
\+ Site Owner (site_owner)
\+ Edit My Own Content (edit_own_content)
\+ Newsletter (newsletter)
\+ Webform Editor (webform_editor)
\+ Submissions Viewer (webform_submissions_viewer)
\- Configuration Manager
