### ISSUE TITLE
Main Menu Navigation Style

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#330]
Since we are moving away from separate themes to a single theme, we need to add in the ability to change the appearance/style of  the main menu navigation on sites. In addition to being able to choose a brand bar color and site name color, users should also be able to choose a menu style.

Below are screenshots of a site in each theme showing what a main menu item looks like when that's the current page:

![Screen Shot 2023-04-18 at 3 11 52 PM](https://user-images.githubusercontent.com/349713/232908216-2eb3f5c2-88a3-4a62-8a7d-93645c7ee3fd.png)
![Screen Shot 2023-04-18 at 3 14 08 PM](https://user-images.githubusercontent.com/349713/232908229-5479ec1b-8a3a-4292-a962-d227443d746c.png)
![Screen Shot 2023-04-18 at 3 13 54 PM](https://user-images.githubusercontent.com/349713/232908235-236a752c-ca5c-4bbb-a4cb-e098450481a4.png)
![Screen Shot 2023-04-18 at 3 13 39 PM](https://user-images.githubusercontent.com/349713/232908239-fe998e69-0e54-49e6-8cab-d4450f70858a.png)
![Screen Shot 2023-04-18 at 3 13 24 PM](https://user-images.githubusercontent.com/349713/232908244-5e8f0870-6009-4f76-8d87-11034875cc6a.png)
![Screen Shot 2023-04-18 at 3 13 09 PM](https://user-images.githubusercontent.com/349713/232908246-676ece9a-8a2b-4452-9bd5-af9b24753bfb.png)
![Screen Shot 2023-04-18 at 3 12 53 PM](https://user-images.githubusercontent.com/349713/232908256-fb6a5ae2-c374-4b50-8419-3f242842f419.png)
![Screen Shot 2023-04-18 at 3 12 40 PM](https://user-images.githubusercontent.com/349713/232908262-f41ff529-5e9a-4998-994a-bb245455b050.png)
![Screen Shot 2023-04-18 at 3 12 26 PM](https://user-images.githubusercontent.com/349713/232908268-84cdd272-545c-415a-a83f-e0b38f7fb93d.png)
![Screen Shot 2023-04-18 at 3 12 14 PM](https://user-images.githubusercontent.com/349713/232908271-a6b6db06-b7eb-43c1-ac14-5b02310f0839.png)
![Screen Shot 2023-04-18 at 3 12 02 PM](https://user-images.githubusercontent.com/349713/232908274-3bc76409-aeef-4aee-9cfb-50ca2b5be70d.png)

**Comment by jcsparks** [comment]
@kevincrafts - there's a lot of sub-themes here : https://github.com/CuBoulder/express_mono/tree/dev/themes

Can you enumerate which ones we need to include for menu styling please?

**Comment by TeddyBearX** [comment]
Sister issue opened as CuBoulder/ucb_site_configuration#24, once that is completed further work should be tagged with this issue.
