### ISSUE TITLE
Inconsistent order of content type names add content page vs add content drop down

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#344]
The ordering of the content type names is inconsistent. The add content page displays the article content types as:
![image](https://user-images.githubusercontent.com/349713/234682880-2954565c-3319-4f6d-a217-735d791f289f.png)
(article, article list)
But the navigation drop down displays them in a different order:
![image](https://user-images.githubusercontent.com/349713/234683031-dfd302de-194b-474c-a252-adbcbcc1b63f.png)
(article list, article)

These should be sorted consistently.

**Comment by jcsparks** [comment]
Unfortunately this is core Drupal functionality that we don't have access to via configuration without modifying core node functionality.  Would like to change but the change is expensive in terms of maintenance and support of core Drupal.
