### ISSUE TITLE
Article Taxonomy Links

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#350]
Taxonomy terms that display on an article should link to a corresponding article list page that is set to be filtered via the term that was clicked.

We found early on that editors wanted more control over the design, layout, and menu position of these pages and linking to the default Drupal taxonomy term view did not meet these needs.  In D7 Express, whenever a new term is created, an article list page filtered by that term is automatically created on the site, with an additional field on the term to store the node ID of the created page.

**Comment by TeddyBearX** [comment]
Duplicate issue – #27
