### ISSUE TITLE
Article Paragraph Types

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#352]
After doing some testing, we'd like to circle back on the article paragraph types:

**Changes:**

Article Content
Remove Media tab from this paragraph type.

Article Hero
Remove this paragraph type. We were not able to think of a use case where we would use this in the middle of an article.

**Additions (new paragraph types):**

Add a Media paragraph that could insert an image or video.  Image would need some sizing options to control the image style used.

Add a Blockquote paragraph type to insert fancy blockquotes with alignment and icon options.

**Comment by jcsparks** [comment]
Thought we had already discussed this.  Backlog for now.

**Comment by jcsparks** [comment]
Removed the Article Hero, no other changes required for the time being.
