### ISSUE TITLE
Article List: Load More

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#370]
Primarily for a11y reasons we need to move from the infinite-scroll solution to a manual clickable solution for loading additional articles on the Article List page.  

Currently additional articles are auto-loaded when scrolling to the bottom of the article list page content.  Instead we should add a "Load more..." link that can be clicked to perform this functionality.

**Comment by TeddyBearX** [comment]
Duplicate issue – #238
