### ISSUE TITLE
CKEditor 5 Plugin: Icons

### ISSUE THREAD

**Issue by timurtripp** [CuBoulder/tiamat-theme#372]
CKEditor 4 has an [Icons](https://www.colorado.edu/demos/web-express/web-express-core/content-styling/shortcodes/icons-shortcode) shortcode. Going to look into the contrib module [Font Awesome Icons](https://www.drupal.org/project/fontawesome) before opening an issue in the CKEditor Plugins repo.

**Comment by TeddyBearX** [comment]
Disappointingly doesn't seem like this contrib module has been updated for CKEditor 5 despite advertising Drupal 10 compatibility.

**Comment by TeddyBearX** [comment]
Font Awesome Icons contrib module shows some work on a CKEditor 5 plugin within the last couple days. I'm going to wait on this one.

**Comment by TeddyBearX** [comment]
There is a [merge request](https://git.drupalcode.org/project/fontawesome/-/merge_requests/30) waiting to be merged in.
