### ISSUE TITLE
Reorder contextual links on blocks

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#376]
Reorder the contextual links on blocks:
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/d6a163cc-4931-4851-a0ea-6da7e6c2c921)

Order should be Edit, Configure, Remove.

**Comment by jcsparks** [comment]
This is built-in Drupal functionality.  It's not something we can easily edit.  Maybe with a admin-sub theme but menus are internal components so it would probably be a hack even at that level.
