### ISSUE TITLE
Content List Block sorting/order of content

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#377]
The content list block only shows the content in the order it was added, trying to either change the sort option, or manual reorder, have no change in the order they are displayed.

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/264da7c2-2d82-438d-b211-8a9b512ae46f)

**Comment by TeddyBearX** [comment]
I'm not able to reproduce this issue with my Content List test blocks in Layout Builder, sorting appears to work fine there. @jcsparks can you look into this?

**Comment by TeddyBearX** [comment]
Update – bug is present but only in Block Layout.
