### ISSUE TITLE
Content List teasers don't show most recent content

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#378]
If a node is added to a content list, and then edited later, the content list does not display the content change:

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/9a015c57-b50b-4f65-8e71-26b5780bf4cd)

**Comment by TeddyBearX** [comment]
Confirmed, my Content List block fails to refresh its cache when a referenced node is updated. I'll attempt a couple possible mitigations.
