### ISSUE TITLE
Cancel button for block edits

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#379]
Can a Cancel Edit button be added when editing custom blocks? Currently when editing a block you only have two options, save, or delete. Also, the back to site link does not work from this state and only returns you to the form.

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/734efcca-d9a4-4fac-b6d0-0023865601bb)

**Comment by jcsparks** [comment]
I don't think we're ready to start modifying the admin theme to add additional functionality at this point.  Will put this in the backlog for now.

**Comment by jcsparks** [comment]
I think there's a close button in the upper right corner now that should work.  As well as the escape key.
