### ISSUE TITLE
Applying Text Block design changes

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#387]
When changing the design options of an existing and placed text block, such as changing the background color, the changes aren't applied.  If you place another block on the page, the previous design changes will appear.

**Comment by TeddyBearX** [comment]
@kevincrafts Is this in Layout Builder or Block Layout?

**Comment by TeddyBearX** [comment]
With block issues it's always helpful to mention which one you're encountering the issue in.
