### ISSUE TITLE
Hero blocks overflow region

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#398]
Hero blocks are extending outside of the region they are placed in:

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/9c358ed4-01f1-4ea3-af4f-7e1a4c95fbaa)

**Comment by jcsparks** [comment]
Aren't Hero Blocks supposed to be edge-to-edge?  If we make it work contained in a column won't that break the full-page option?

**Comment by kevincrafts** [comment]
Ok so I'm thinking what needs to change here is that the section needs an option for displaying contents as full width, or content width. Then hero blocks would just fill up whatever space is made available for them.

I've seen sections having this same issue. Yes many of their uses go edge to edge, but they should be able to be used within the content area as well.

I'll see if I can draw out a diagram that we can talk about this more on Monday.

**Comment by jnicholCU** [comment]
This has been cleaned up before the claro/10.2 move
