### ISSUE TITLE
Linking to expandable content

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#403]
Site editors need the ability to link to a specific expandable item, have it opened, and scroll the user to that content. This includes site editors that might be working on a different site and need to link to an accordion on a different site that they may not have editor access to.

For example: https://www.colorado.edu/commencement/faqs#do_we_need_tickets_for_the_ceremony_-348 - in this case, the url is updated on each accordion click and makes it easy for a site editor to copy and paste that link.

**Comment by jcsparks** [comment]
Sounds like our accordions don't have anchor tags added by default or if they do, they don't auto-open when navigating there directly.
