### ISSUE TITLE
Link Field Description

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#406]
In our tests, the link field description was found confusing. Can we alter it from:

Start typing the title of a piece of content to select it. You can also enter an internal path such as /node/add or an external URL such as http://example.com. Enter <front> to link to the front page. Enter <nolink> to display link text only. Enter <button> to display keyboard-accessible link text only.

to:

Start typing the title of a piece of content to select it. You can also enter an internal path such as /about or an external URL such as http://www.colorado.edu. Enter <front> to link to the front page.

**Comment by jcsparks** [comment]
I'm not sure that's something that we can easily change... it's the default built-in help text for the unified internal/external URL entry widget for Drupal.

Any help text we add would be in addition to this from the content schema side of things.
