### ISSUE TITLE
Content Grid Cell Alignment

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#408]
Content grid cell alignment should be consistent on columns and card displays. Cells should always align left.

![Screen Shot 2023-06-05 at 11 38 24 AM](https://github.com/CuBoulder/tiamat-theme/assets/349713/eb8eb40e-cf57-4781-822a-39b8caf580a8)

![Screen Shot 2023-06-05 at 11 38 05 AM](https://github.com/CuBoulder/tiamat-theme/assets/349713/597578af-8be5-48f8-a6e1-9d2679b2fff0)

![Screen Shot 2023-06-05 at 11 44 43 AM](https://github.com/CuBoulder/tiamat-theme/assets/349713/28065e5b-14f4-4332-96c0-b586011fbf9f)

![Screen Shot 2023-06-05 at 11 44 57 AM](https://github.com/CuBoulder/tiamat-theme/assets/349713/e036dff5-9573-4e10-9a42-2b793287b9b7)

**Comment by jnicholCU** [comment]
Closed with #415
