### ISSUE TITLE
Bug in content sequence block template

### ISSUE THREAD

**Issue by tirazel** [CuBoulder/tiamat-theme#418]
There seem to be twig syntax errors on lines 44, 89, and 182 in block--content-sequence.html.twig.  If I remove the 'if key|first != '#'' section at the end.  My twig is rusty, so I'm not sure what the intended functionality is.

**Comment by TeddyBearX** [comment]
I don't know why they removed this syntax from Twig. It works fine in other templating languages like Nunjucks and is cleaner then having a nested `if` block. Why can't we have nice things 🤦🏻‍♂️
