### ISSUE TITLE
Slow CSS performance

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#436]
When navigating through a site logged in, whether through the front facing pages or the administration pages, I see the admin menu items for a few seconds, depending on how long it takes the rest of the page to load.

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/20488a9c-490a-432e-80e7-a1c14983d2ad)

**Comment by jcsparks** [comment]
This seems to be a known issue with Admin Toolbar : https://www.drupal.org/project/admin_toolbar/issues/3369118

Hopefully will be fixed in the near future, looks like there's already a community contributed patch.
