### ISSUE TITLE
Custom Logo access should be restricted to architects and developers

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#439]
Due to the strict use of custom logos we need to lock this down further. We can't give permissions to this to site owners/editors/etc.

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/9214bc09-f40b-4010-9a11-cd0be63457b3)

**Comment by TeddyBearX** [comment]
From my testing this is already locked down with the permission "Edit advanced site settings" assigned to Architect and Developer. @jcsparks can you confirm this is the case for you?

**Comment by TeddyBearX** [comment]
Closing as not planned – already resolved in CuBoulder/tiamat-theme#270
