### ISSUE TITLE
Can't add media due to overlay

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#440]
When trying to add media, either by a field or the WYSIWYG, when you try and upload an image you are eventually blocked by an overlay that prevents you from adding alt text and saving.

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/da8998d0-74fc-4015-bb3b-d2b05716e2b3)

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/6eea158a-c027-439e-ab3f-cdb4365b65fc)

**Comment by TeddyBearX** [comment]
D10 specific issue.
