### ISSUE TITLE
Block Design

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#443]
In D7 Express, users have the ability to design any block they create. These design options include:

- Adding an icon to the title
- Icon settings
-- Icon position
-- Icon color
-- Icon size
- Heading level for block title (h2-default, h3, h4, h5, h6, strong)
- Heading alignment (default-left, centered)
- Style - these are mostly background colors but also have a couple other options. None, white, light gray, dark gray, tan , light blue, medium blue, dark blue, light green, brick, outline, underline
- Text size
-- Block title font scale (default/increase/decrease)
-- Block content font scale (default/increase/decrease)

Currently there are only background color options only on text blocks. These should work on all block types.

This was influenced (at the time) by the Block Class module (https://www.drupal.org/project/block_class) with a redesigned UI that would allow users to choose different options vs entering class names into a text field.

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/466b4d4e-36da-4707-ac56-33739016750f)

There's a newer module that is D10 compatible that introduces additional fields to target the block wrapper, title, and contents: https://www.drupal.org/project/block_classes

For migration, this information was stored in the express_block_designer table.

There was also an additional feature that allowed you to save block settings and apply those to a series of blocks rather than having each block be set individually. I'm not totally sure how much that has been used, but you can see how many of these have been created in the express_block_designer_themes table.

CSS can be found here: https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/express_block_designer/scss/express-block-designer.scss
https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/express_block_designer/scss/modules/_global.scss
https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/express_block_designer/scss/modules/_colors.scss

**Comment by jnicholCU** [comment]
This is currently possible for layout builder through that project but it does rely on a patch that breaks being able to change forms in Block Layout. 
This is supposedly being patched in 10.2 this December
