### ISSUE TITLE
Inconsistent and confusing labels

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#454]
When trying to edit block content, users are given different options depending on how the block was placed. If the block was placed with Layout Builder, the user sees the following options:

![Screen Shot 2023-07-20 at 11 16 10 AM](https://github.com/CuBoulder/tiamat-theme/assets/349713/30bb82d8-63f6-42ab-a0f6-11f66ebf730e)

However, if a user places a block with Block Layout, they get this set of options:

![Screen Shot 2023-07-20 at 11 18 54 AM](https://github.com/CuBoulder/tiamat-theme/assets/349713/cfd2e6fe-8c43-4227-b2f8-1bbb10edcb08)

Where this gets really confusing for the user is that "Configure" does different things depending on how the block was placed. In Layout Builder, configure IS the edit link, where in block layout, configure only lets you change the title and region but not the actual contents.

Is there anything that we can do to make these labels consistent? Otherwise I think this is going to be a very confusing issue with our users.

**Comment by kevincrafts** [comment]
Can we look into this? https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Menu%21menu.api.php/function/hook_contextual_links_alter/10

**Comment by kevincrafts** [comment]
Also, while we may be trying to restrict how many users have access to the block layout tool, the reality is that we have thousands of sites that have blocks in these other regions and even if we are limiting access to the layout part of this, users still need to be able to edit block content that is in those regions which is where this link label issue is going to show up.

**Comment by jcsparks** [comment]
Keep it close to core... not going to modify currently.  May revisit in the future.  Closing for now.
