### ISSUE TITLE
Reordering content in block editor

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#455]
When editing a block that has draggable content, such as content grids, content row, sliders, etc, it is difficult to drag and reorder content due to the size of the modal and the size of the displayed fields.

In some cases, like with the slider, you can only drag one element at a time. Dragging the first slide to be the second slide for example.

In other cases, like content grids, it is nearly impossible to drag and reorder content unless you position the contents to where you can see the content you want to reorder and the next content that is in the direction you want to drag.

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/886d0c59-0a0b-4315-a27b-ad9a9143ed0e)

Even if you do this, you can only drag one position at a time.  For example, if you have 6 cells in a content grid and want to reorder them to have the last cell be first, you will need to position your modal contents, drag once, reposition your modal contents, drag again, and repeat this as many times until it's in the position you want. For this example that would be 5 repositions + 5 drags.

I worry that this is a frustrating experience for users to do in order to reorder the contents of their blocks, and it's not even clear that you would need to position your modal window contents just right in order to even start the process.

**Comment by jcsparks** [comment]
Should be better user experience now in with Claro admin theme.  Collapse the blocks makes them easier to reorder.
