### ISSUE TITLE
Profile Clean-Up

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#501]
It looks like there's a bunch of config that we may not need in the config/install directory, (e.g. anything with claro in the filename). 

Additionally we should see if we can remove the uuid lines from the top of any yaml files that still contain them.  I believe we don't need or want these in the install profile config/install files.  See if we can remove those lines and verify that install still works correctly.

**Comment by tirazel** [comment]
_core.default_config_hash might also need to be removed.  Hold off on removing it for now, though.

**Comment by timurtripp** [comment]
> _core.default_config_hash might also need to be removed. Hold off on removing it for now, though.

I've been removing this from my config files.
