### ISSUE TITLE
WYSIWYG: Anchor Button

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#502]
Content editors need the ability to add anchors to their content and there doesn't seem to be a button available to add to the current editor.

The anchor button should be added right after the link button.

**Comment by jcsparks** [comment]
If we're making changes to the CK editor toolbar can we get all of the changes at the same time?  I know we've been talking about extending the toolbar to 2 lines to fit all of the buttons.  Would be nice to do that all at the same time if possible.

**Comment by jcsparks** [comment]
We've resolved the multi-line concerns but it doesn't look like out-of-the-box CK5 has an anchor tag plugin.  Will need to see if this is coming or if there's another contrib module out there that adds this in, hopefully we don't have to write one ourselves.
