### ISSUE TITLE
Order of sections in node edit admin sidebar

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#504]
I checked with Jeremy yesterday and he said he thought reordering the sections in the sidebar of the nod editor was possible.

1. Publish Status/Revision Info
2. Menu
3. URL Alias
4. Sitemap
5. Social Sharing
6. Meta tags (currently missing)
7. Third Party Services
8. Scheduling options (currently missing)
9. Promotion Options
10. Authoring Information

**Comment by jcsparks** [comment]
Sounds like we're going to skip the metatag stuff for now. 

https://www.drupal.org/project/scheduler - for scheduling
