### ISSUE TITLE
Add a Created column to content overview screen

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#505]
Add a created column to the content overview screen for users to be able to sort content by when it was created, allowing them to see/find content that may be outdated or stale.

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/5eb5ff57-a70c-4f40-bdcf-23e6255d7629)

**Comment by jcsparks** [comment]
This is a view that we can add the column to.

**Comment by timurtripp** [comment]
Added the column but can't figure out how to get it to enable sorting by that. It's appearing as a static column without sorting like the "Author" column.
