### ISSUE TITLE
Remove Features and ucb_custom_entities?

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#507]
Question : can we eliminate the dependance on Features?  

1. Determine if we can get a working installation by moving the configuration for our custom entities out of a module created by features and into the installation profile instead.  
2. Will we be able to make configuration updates to these entities after installation via a config import?

**Comment by timurtripp** [comment]
[Config profile](https://www.drupal.org/project/config_profile)
