### ISSUE TITLE
Menus and Sidebars

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#528]
D7 Express is using : https://www.drupal.org/project/menu_block to create sub menus automatically off of children elements of the main menu and placing those in the sidebar of the site by default.  

Would like to keep the same functionality and UX if possible.  Examine what we can do with the D10 version of this module and see if we can recreate that user experience on the new codebase.

**Comment by timurtripp** [comment]
Duplicate issue – CuBoulder/tiamat-theme#267
