### ISSUE TITLE
Layout Builder Button

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#541]
If you've added a dark color or background image to a section, the add block button can be very difficult to see and read.

One idea would be to set the background color to white since it would match the display of the button when there is no background set and would still have reasonable contrast.

<img width="1366" alt="Screen Shot 2023-11-08 at 2 45 22 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/e382ef44-d188-47e7-9633-951aa434ff84">

<img width="1366" alt="Screen Shot 2023-11-08 at 2 47 35 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/0b8776f2-df53-40b5-b8bb-17b0b3b73704">

**Comment by jcsparks** [comment]
No longer an issue with the change to Claro.
