### ISSUE TITLE
Block Permissions

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#542]
All roles, except for content editor, are missing all the permissions for blocks (created, edit, delete, etc). These permissions are used for creating and editing blocks that are placed through Block Layout (admin/structure/block).

<img width="1608" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/af81f043-2c35-4326-8953-6eea1a13a9e4">

Taking a bit of a guess here and thinking we need developers, architects, and layout managers to have all the permissions.

Site managers and content editors should have the edit and revert permissions.

I've got some thoughts/questions about the delete permissions that I'll add to a meeting agenda.

**Comment by jcsparks** [comment]
We've already merged in a fix for this... will be deploying to the sanboxes in the very near future.
