### ISSUE TITLE
Can't Add Media

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#544]
Emily's been trying to work with some of the block types and keeps running into an issue where the media won't be added or uploaded.

Trying to replicate the issue I see these errors in the js console: 

"ResponseText: {"message":"The following permissions are required: \u0027create video_reveal block content\u0027 AND \u0027access block library\u0027."}"

ResponseText: {"message":"The following permissions are required: \u0027create hero_unit block content\u0027 AND \u0027access block library\u0027."}

When looking at the permissions page, these permissions don't even exist.

**Comment by jcsparks** [comment]
Believe this has been resoled and is no longer an issue.
