### ISSUE TITLE
Article Taxonomy Links

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#546]
The tag and category links on articles should link to article list pages rather than the taxonomy pages so editors have control of placing those pages within the site menu structure and adding additional content via the article list page body field and via blocks.

**Comment by jcsparks** [comment]
Backlogging for now... we may decide this change isn't required after discussion with the larger UI/UX team.

**Comment by jcsparks** [comment]
Discussed with UI/UX team and they're okay with linking to taxonomy pages for the time being.
