### ISSUE TITLE
Spacing below main menu

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#548]
When content is placed below the main menu, there should not be space between the menu and the section/content.  The exception to this is when it's just the page title.  

When content is placed above the page title, there should be some space above it.

Breadcrumbs should be displayed with the page title and should not be split if content is placed above the page title.

<img width="1891" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/ed7d6b09-5475-4658-b52a-04802a874d41">

**Comment by jnicholCU** [comment]
@timurtripp Partially. I was actually working on this in another issue related to layout builder and such. I'll go ahead and assign this ticket to me.

**Comment by timurtripp** [comment]
@jnicholCU I think you're in a better position to address this since you have sister issue #777 assigned to you.

**Comment by timurtripp** [comment]
Unfortunately it's still an issue. The breadcrumb change Kevin is asking for seems like a substantial refactor of how our breadcrumbs work so I'd like to talk more about that one.

**Comment by jnicholCU** [comment]
We had a conversation about this with the UI/UX team a couple weeks ago and I forgot to update this ticket. 
The breadcrumbs being in its own region makes this unfeasible for the time being. Especially now that the title is movable. 
The rest of this ticket will be fixed in my upcoming PR.
