### ISSUE TITLE
Theme Design Settings

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#551]
Secondary Menu

- Secondary menu position default value should be above
- Button/Color option is for inline links only. Links positioned above the main menu should be text only and not appear as buttons.
- Color options for buttons are blue, gold, gray, none.
- Button links don't have proper contrast to be accessible
- Button links are inconsistent in font weight, spacing (between buttons and from edge of navigation bar)
- Position of navigation bar is inconsistent on rise option depending on the position setting for secondary navigation:
<img width="1677" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/d33409fa-d6b9-460c-9d28-407aac0909db">

- Tradition menu shows two line for active state - should be only the gold line

<img width="717" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/c802264d-4fba-45b4-bc14-033e2235c800">

**Comment by jacob-korf** [comment]
- [ ] Secondary menu position default value should be above
- [ ] Button/Color option is for inline links only. Links positioned above the main menu should be text only and not appear as buttons.
- [ ] Color options for buttons are blue, gold, gray, none.
- [ ] Button links don't have proper contrast to be accessible
- [ ] Button links are inconsistent in font weight, spacing (between buttons and from edge of navigation bar)
- [ ] Position of navigation bar is inconsistent on rise option depending on the position setting for secondary navigation:
- [ ] Tradition menu shows two line for active state - should be only the gold line
