### ISSUE TITLE
Adding video media from wysiwyg doesn't display after save

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#561]
If you add video media from in a wysiwyg it will show as added in ckeditor but on save it does not display. I'm assuming this is due to a twig template not being fleshed out.
<img width="584" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/94021017/0654254c-2aad-4b46-8cf3-47861909afa8">

**Comment by patrickbrown-io** [comment]
This seems to be a problem with how the the alignment options currently work and the video. If you leave the video on the default option, Break Text, the video shows up. Using any of the other alignment options prevents the video from displaying but if you inspect the wrapping div and manipulate the alignment class, you can get it to pop up again
