### ISSUE TITLE
Hero Unit Blocks Missing Layout Builder twig attributes

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#562]
Hero units are not draggable or viewable properly in layout builder. The twig template is missing the attributes that allow this.

**Comment by timurtripp** [comment]
@jnicholCU You might have to help with me on this since you're more familiar with how the Hero Unit is supposed to work. I fixed the draggability but may have introduced other problems in my commit to the `issue/562` branch.

**Comment by timurtripp** [comment]
We may also be able to add a fix for #565 along with this.

**Comment by jnicholCU** [comment]
Still haven't heard back from the other team about what we need to do for #565 so that's in limbo.

**Comment by timurtripp** [comment]
Got it. I'll backlog #565 for now.
