### ISSUE TITLE
Logout Error

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#590]
When trying to logout of a Web Express site I receive an Unsupported Request error:

<img width="704" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/3c2dff47-b5fd-4b53-b2da-00a348837ebf">

**Comment by jcsparks** [comment]
This is a known SAML issue, I don't think we can fix this at our level.  It will have to be part of a change to the way FedAuth works.
