### ISSUE TITLE
Linking Icons in WYSIWYG editor

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#604]
When just adding an icon with text in the WYSIWYG editor, the icon is unable to be linked.  If you select the icon and text, the link is only applied to the text. If you select just the icon the link button is unavailable.

https://www.drupal.org/project/ckeditor5_icons/issues/3409876

**Comment by timurtripp** [comment]
A fix is ready for review in the CKEditor 5 Icons project.

**Comment by timurtripp** [comment]
Fix reviewed and merged into the dev branch, marking as resolved.
