### ISSUE TITLE
Edit link on slider blocks

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#609]
When you hover over a slider block, an edit icon appears in the top right corner, but when you try to click on it, the icon disappears when you hover over it:

<img width="1644" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/d2e5149c-278e-4724-aa93-7a96d4c2011d">

https://live-ucbdev-sandbox-emily.pantheonsite.io/slider-block

**Comment by timurtripp** [comment]
The edit link is coming from the image media item, not the block itself. The next button of the carousel takes up the entire right side and is on top of the image, so the edit link disappears when trying to click it as you are then hovering over the next button instead of the image.

**Comment by patrickbrown-io** [comment]
No longer an issue
