### ISSUE TITLE
Disabling Menu Items

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#627]
In Drupal 7 we used the contrib module [Disable Node Menu Item](https://www.drupal.org/project/disable_node_menu_item) which allows editors to place content within the structure, but not have the menu item appear.

An example of this usage would be if you had a faculty page and placed all the faculty person nodes as children of that page. This would keep the breadcrumbs and the active trail menu styling for those person pages but not fill up the sub navigation menu with links.

Unfortunately that module hasn't been updated since D7, however, they recommend the [Menu Position](https://www.drupal.org/project/menu_position) module that is D10 compatible.  Reading through the module page, it sounds like this module could solve some of the things people were using Context for as well.

https://www.drupal.org/project/disable_node_menu_item
https://www.drupal.org/project/menu_position

**Comment by jcsparks** [comment]
There is a workaround.  May revisit later but not going to add it for the time being.
