### ISSUE TITLE
Mega Menu

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#629]
A few of the higher profile sites, such as /business, use a mega menu in their navigation.

The Express 3.0 version of Mega Menu is a custom entity that can be attached to a specific menu item.

**Fields**

- Label (for admin use only)
- Heading (Displayed at the top of the mega menu and linked to the menu item's url)
- Text Above (WYSIWYG)
- Links (A field collection with no limit)
-- Label (Heading at the top of link list)
-- Link field collection with no limit)
--- Link field (limit 1)
--- Description (text field, limit 1)
- Text Below (WYSIWYG)

**Setup**

- Individual mega menus are created
- mega menus are attached to main menu items via a select menu showing all available mega menus
-- mega menus can be enabled/disabled by a toggle switch on the menu item

**Display**

- The mega menu in 3.0 displays only on desktop browsers. Needs additional testing for mobile menu use.
- Main menu links would get a downward angle icon (https://fontawesome.com/v4/icon/angle-down) to indicate there was a mega menu on that link
- Clicking on the main menu link would display the mega menu, the heading of the main menu is linked to the original menu item's url in order to allow the user to visit that page
- Display of the Links collections are in columns, depending on the number of collection items:
-- <= 3 - 3 columns
-- 4 - 4 columns
-- 5 - 5 columns
-- 6 - 6 columns
-- 3.0 code didn't account for more than that and would default back to 3 columns of links
-- If the Text Above field is used, this is considered another column. For example, Text Above + 3 Link collections would display as 4 columns
-- Text Below is displayed below the link columns

**Screenshots**

Mega Menu Create/Edit Screen
<img width="673" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/d6e6ec19-3e64-42f9-b845-3888289c2a2b">

Attaching a Mega Menu to a Menu Item
<img width="505" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/650c9236-2120-45e9-a253-8653772597b5">

Navigation showing Mega Menus are attached to menu items (downward angles indicate which links have mega menus)
<img width="1057" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/a94d241c-b0b1-40ca-8049-83d4c200fc96">

Mega Menu Expanded
<img width="1467" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/a0940e6b-4fae-4ce9-bc1a-8840ccafe171">

**Comment by jcsparks** [comment]
Will need some solution for this.
