### ISSUE TITLE
Sidebar Configuration Updates

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#633]
We're going to set the Right Sidebar as the default option and hide the theme setting to change it from the right to the left as the main sidebar. 

We should be able to remove the Left Sidebar region from the Block Layout and Region definition and the Right Sidebar region for either based on the theme variable set in the admin settings.  

Additionally we want to default the secondary nav block to be placed and properly configured in the Right Sidebar region.

**Comment by timurtripp** [comment]
By _hide_, are you wanting the setting to go under Advanced in the Appearance and Layout settings? It's currently under Miscellaneous.

**Comment by timurtripp** [comment]
Can you clarify what you mean by "properly configured", is the default configuration for the block okay?
