### ISSUE TITLE
Admin modal window close button not visible

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#640]
When opening up a modal window, in this case it was adding a custom block, the close icon is the same color as the window header and is not visible.

The white circle in the image below is from hovering over the close link. 

<img width="1733" alt="Screenshot 2024-01-25 at 8 03 13 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/fab7cb0c-4a4c-46d9-bea0-d778bf96e592">

**Comment by patrickbrown-io** [comment]
Resolved with Claro, closing
