### ISSUE TITLE
Subnavigation in Mobile Menus

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#647]
Without changing how the main navigations works for desktop we would like to be able to include the sub-navigation elements in the main menu in the mobile context.  Which is to say that in mobile you should be able to view not just the top level elements of the main navigation but also the children elements (within reason... iirc, Drupal limits this to three levels of depth).  

I think to do this we'll need to modify the main menu to render the children elements in the DOM but only display the top-level in the desktop view.  

There may be more efficient solutions however and I'm open to hearing other solutions.  This will be a stopgap solution before a full rework of the mobile menu UI/UX.  If we can make this work we'll plan on a more comprehensive rework of the mobile menu interface after the migration is well in hand.

**Comment by timurtripp** [comment]
We need to discuss how best to handle this as expanding all the child elements is going to make the menu big and unwieldily.

**Comment by timurtripp** [comment]
Maybe to do it only for the active item. Taking a look at D7 Express and it doesn't seem like they are expanding the children at all there.

**Comment by timurtripp** [comment]
<img width="686" alt="Screenshot 2024-02-08 at 10 17 48 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/22628823/d5357d16-6eb1-4b52-a499-0567d5a2b21b">
