### ISSUE TITLE
Issues adding an Image Gallery Block

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#656]
When adding an image gallery block after adding images and clicking the button to add the block I get stuck with a spinner and an error message that appears behind the modal:
<img width="2248" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/da241a5f-93b1-4141-a001-1de02d09f06a">

My JS console shows a 500 error. Trying to click away and go back to view the page results in a php error: 

Twig\Error\SyntaxError: Unexpected token "name" of value "if" ("end of statement block" expected). in Twig\TokenStream->expect() (line 32 of /code/web/themes/custom/boulder_base/templates/block/block--image-gallery.html.twig).

**Comment by timurtripp** [comment]
Duplicate issue: #642

**Comment by jacob-korf** [comment]
This issue was resolved with the image gallery bug fix on #655
