### ISSUE TITLE
Content Sequence UI elements should be the same blue color as links/buttons

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#669]
The color of these UI elements should be the same color blue as links/buttons - #0277BD

<img width="816" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/dfb4d215-2cf3-42da-9d4d-b1072b50334e">

**Comment by jacob-korf** [comment]
From talks with Kevin, this issue seems to be non-replicable on either side. The arrows on the side of the scrollbar and the arrows on the bottom of the content sequence seem to be the correct color both in code and on the website.
