### ISSUE TITLE
Collection grid showing term ids for filters instead of term names

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#679]
I created a collection grid but the filters are showing ids instead of names:

<img width="445" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/c01a34ff-3869-472a-b44d-75c19dde09dd">

**Comment by timurtripp** [comment]
May already be fixed

**Comment by timurtripp** [comment]
via #661 (merged)

**Comment by timurtripp** [comment]
I'm going to close this as resolved, but feel free to reopen if you're still having the issue following the sandbox updates.

**Comment by timurtripp** [comment]
Duplicate issue: #649
