### ISSUE TITLE
Issue Display

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#704]
A few issues on the issue content type display:

1. 2 images appear on the side, due to there being two separate image fields. Not sure which one is supposed to be used.
2. Issue text field has a dark gray box vs the light box you'll see on the current version: https://www.colorado.edu/coloradan/fall-2022

<img width="1192" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/74d41c72-a277-4591-830e-6af441758b08">

3. The read more text uses capital letters vs capitalizing them with css.  Is there a reason why the teaser view of articles changes throughout the site vs using the same teaser view mode? Articles referenced in issues and content lists seem to be totally different displays than the view modes referenced in article lists.

**Comment by patrickbrown-io** [comment]
Discussed with kevin, the left column is actually the body field and can be used with WYSIWYG and CKEditor to make various layouts like 
<img width="846" alt="Screenshot 2024-03-06 at 10 00 06 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/85851903/33738108-1f3d-43a9-88ca-fe281bd8e12d">

and 
<img width="370" alt="Screenshot 2024-03-06 at 10 02 17 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/85851903/81e743d5-dacd-4f8d-b151-9016fc1113e0">

Will remove the secondary image field, address the left-hand column, and fix the Teaser Article view
