### ISSUE TITLE
Email Newsletter

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#706]
Did some testing with email newsletter and found some issues. I'll document them here but there's also an attached image with notes below:

**Display issues**

- Newsletter type title is missing
- View on site link isn't accessible
- Featured display thumbnails should be cropped to a 2:1 aspect ratio and have a width set to the same as the email to reduce file size
- Section headers should be 20px
- Article titles should be 18px
- Category links should be 10px and a dark gray that is accessible with the light gray background
- Article text should be trimmed to 50 words plus "..." unless a summary is used
- Teaser thumbnails should be a max of 130px but allowed to scale downwards if viewed on a smaller device

**Other issues**

- Unpublished articles should not display in a newsletter, but would it be possible to indicate if unpublished content was being referenced?
- There should not be a limit on the number of newsletter blocks that can be added
- Custom content should not include a category field
- Missing ability to add social links to html email footer

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/10e7f6c8-2c79-422d-afad-e7c6ce9cefb8)

**Comment by patrickbrown-io** [comment]
**Display issues**

- [ ] Newsletter type title is missing

- [ ] View on site link isn't accessible (Can not replicate, the "View on Site" works on Kevin's test site and the email HTML version)

- [ ] Featured display thumbnails should be cropped to a 2:1 aspect ratio and have a width set to the same as the email to reduce file size

- [ ] Section headers should be 20px

- [ ]  Article titles should be 18px

- [ ] Category links should be 10px and a dark gray that is accessible with the light gray background

- [ ] Article text should be trimmed to 50 words plus "..." unless a summary is used

- [ ] Teaser thumbnails should be a max of 130px but allowed to scale downwards if viewed on a smaller device

**Other issues**

- [ ] Unpublished articles should not display in a newsletter, but would it be possible to indicate if unpublished content was being referenced? 

- [ ] There should not be a limit on the number of newsletter blocks that can be added

- [ ] Custom content should not include a category field

- [ ] Missing ability to add social links to html email footer
