### ISSUE TITLE
Article list headlines have wrong markup

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#718]
Article headlines, when displayed in an article list block, should not be h2 headings. Not only does this cause issues with heading hierarchy on a page due to the block title also being an h2, but the text size is much too large.  

<img width="1401" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/a2a44e46-44c6-4058-8a89-2c8b5063d2af">

**Comment by patrickbrown-io** [comment]
@kevincrafts 

Theres a mix of headers used in D7 across the various Article block styles.

Here's what I've found...

- **Article List Block**:  D7 uses `<strong>` wrapped a tags for a bold effect (no demo)
- **Article Grid block** has them as h3s,  https://www.colorado.edu/demos/web-express/add-bundles/article-grid-block
- **Article Feature Block** feature article is an h2, others in the list are simple <a> , https://www.colorado.edu/demos/web-express/add-bundles/article-feature-block
- **Article Slider Block** - uses h3s, https://www.colorado.edu/demos/web-express/add-bundles/article-slider-block

Is this all correct? Will use this ticket to address all Article Block headers all in one pass
