### ISSUE TITLE
Articles without thumbnails

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#731]
If an article does not have a thumbnail added, it should not be indented in article lists:

<img width="1192" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/93b80888-d5f2-4a44-b534-d00f6064d762">

**Comment by patrickbrown-io** [comment]
@kevincrafts 

I tested this out on a fresh local dev install, as well as checked out your sandbox site, can not replicate. We definitely fixed this display in a past ticket on the Article List page. I am also seeing the same behavior on the Article List block as well... so I'm closing this issue for now.

<img width="1444" alt="Screenshot 2024-03-11 at 10 57 33 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/85851903/6fdcc8b5-7524-4a46-a8b8-1cd3c89c60c4">

<img width="1315" alt="Screenshot 2024-03-11 at 10 58 44 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/85851903/bd6d9f17-f5e0-46cb-9557-705efa0a43df">
