### ISSUE TITLE
Text field content aligning

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#739]
Sometimes text in a ckeditor block won't align center even when the option is chosen. 
Need to see if it is replicable in dev/sandbox environments.

**Comment by patrickbrown-io** [comment]
Just tested -- I'm not able to replicate this in a dev environment or on a sandbox site. Text in the box aligns center as well as the box title.

I tried adding CK Boxes to the body, and in Text Blocks, is there somewhere specific this is occurring?

**Comment by patrickbrown-io** [comment]
![Image](https://github.com/CuBoulder/tiamat-theme/assets/85851903/2843ca39-59e9-4831-9de5-f27737384c15)

**Comment by jcsparks** [comment]
This is a copy/paste issue from the previous version that used inline styles instead of classes to do alignment.
