### ISSUE TITLE
Block Style Tags Visible in Render

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#740]
The Block Style tags, e.g. 
`bs-content-scale-default bs-heading-align-default bs-heading-style-default bs-icon-color-default bs-icon-position-default bs-icon-size-default bs-title-scale-default h2`

are showing in the render of some of the blocks, noticing it on the Hero block as well as the Event Calendar block.  

You can see it on https://live-ucbdev-sandbox-demo.pantheonsite.io/

**Comment by jnicholCU** [comment]
These tags were getting added because we were just running a straight `{{ content }}` on those two blocks because they were so minimal. Just updated to target the correct fields. Will be in my big PR coming up.
