### ISSUE TITLE
Videos in a Text Block not working

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#741]
Videos in a Text Block aren't rendering after the most recent update.  Not sure if we broke something with the addition of the block styles or if there was an oEmbed change in Drupal 10.2.4.  But these worked last week but no longer render in the latest build of the code.

**Comment by timurtripp** [comment]
Can't reproduce. It looks fine here for me

![Image](https://github.com/CuBoulder/tiamat-theme/assets/22628823/111436a3-c597-4939-967c-ce88b143fe2d)

**Comment by timurtripp** [comment]
Figured out how to reproduce – only happens if the video is the only thing in the text block
