### ISSUE TITLE
Section Padding

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#754]
Is there a way to remove the padding on a section? When a hero is added, it gets padding on the top and bottom of the hero:

<img width="1582" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/307320f4-e5f9-4418-b1a5-96d64df513a4">

I also know there's some sites out there where text blocks with images have been added to layouts without a containing section and the images are meant to go all the way across: https://www.colorado.edu/globalclimatesummit/summit/day-1-impacts

Perhaps the sections could get a background option of "none" that would remove all padding?

**Comment by jnicholCU** [comment]
The hero issue here has been fixed in a previous update.
However I think we discussed the text box image situation previously and decided that shouldn't be the process going forward. I will bring it up again in our next meeting.
