### ISSUE TITLE
Form Confirmation

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#756]
If a form is set to show a confirmation message,  Here's some screenshots of configurations and results:

Page:
The confirmation title does not display and the message appears at the edge of the page instead of in the content area.
<img width="898" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/0f145338-258e-4bd5-abce-b792bef65035">

<img width="1871" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/62308f53-4997-4500-ae0b-b03fed24bc41">

Inline:
The confirmation title does not display and the message is in a box
<img width="899" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/764cd645-14f4-479d-af8e-2c44c0e62454">

<img width="1345" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/93eeff0e-9e16-4373-a587-a84535368cf9">

**Comment by timurtripp** [comment]
The "Page" confirmation (missing padding + not displaying the title) is resolved via CuBoulder/tiamat-theme#982 and the "Inline" confirmation showing up in a box is resolved via CuBoulder/tiamat-theme#774. It doesn't look like the title is supposed to display on the "Inline" confirmation, only on the "Page" and "Modal" ones, hence why Webform labeled it as "Confirmation page/modal title". Marking as resolved.
