### ISSUE TITLE
Moving the body field on a basic page layout

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#761]
If you make a new section with columns and move the basic page body field into one of those columns, there's additional padding on the field:

<img width="497" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/6e3259ea-41f7-4cdc-99e6-2ff76975d7b2">

**Comment by patrickbrown-io** [comment]
Can not replicate on dev environments or your test site: https://live-ucbdev-sandbox-kevin.pantheonsite.io/basic-page-body-test
Created 2, 3 and 4 column layouts to test for extra padding.



![Image](https://github.com/CuBoulder/tiamat-theme/assets/85851903/15ceea53-2888-4d77-867e-7d2785d58265)
