### ISSUE TITLE
Video Reveal Issues

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#766]
There's a few issues that have come up with the video reveal block since the last couple updates:

1. The letter A appears above the play button text (screenshot below)
2. There's a gray bar at the bottom of the still image (screenshot below)

<img width="1379" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/e801dab1-2d78-424b-8862-7f751ccb1a7a">

3. After clicking on the play button and revealing the video, the video player is not the same size as the block. The screenshot below is the same block as the screenshot above.

<img width="1469" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/63b57ae0-a567-4620-8219-baf5f88b063f">

**Comment by jcsparks** [comment]
Already fixed the issue about the capital "A" : #797
