### ISSUE TITLE
Forms aren't responsive

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#768]
Due to a width attribute on forms, and sizes on fields with no css width, forms aren't responsive and can extend out of bounds off the edge of the screen causing a horizontal scroll bar:

<img width="614" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/f94f3218-3dac-4e89-8e81-ae7da1c34bcd">

**Comment by timurtripp** [comment]
Sister issue: CuBoulder/tiamat-theme#755
