### ISSUE TITLE
Blocks inserted in edge to edge sections should go edge to edge

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#778]
If a block is inserted in a edge to edge section, that block should go edge to edge, regardless of what type of block it is.

HOWEVER, this should not keep the block contents at content width.

<img width="1525" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/ec6d6cf9-1dd2-4667-9e9f-f83deef36ea1">

**Comment by jcsparks** [comment]
Out of scope for the time being.  Intent is to create custom blocks that are designed to work in the edge-to-edge context going forward.
