### ISSUE TITLE
Slider Block Title

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/tiamat-theme#788]
The Slider Block Title does not display as an H2.
![sliderblock title](https://github.com/CuBoulder/tiamat-theme/assets/16137919/2b3bba44-c8e3-4116-84fd-1d5e0cb72121)

I also changed the heading style in the block designer tab to H3 and centered and the block titled stayed justified to the left, the heading style did change but I was not sure if this was and H2 or H3
![sliderblock titleH3-centered](https://github.com/CuBoulder/tiamat-theme/assets/16137919/222b9129-edf7-4549-ab87-dae54e1b2264)

The block title styling is a little buggy though.

This is the site with the issue
https://live-ucbdev-sandbox-docs.pantheonsite.io/block-content/slider-block

**Comment by jcsparks** [comment]
I thought we already fixed this... not sure if this is something that was fix but the fix hasn't been applied to the sanboxes yet or if this is still an outstanding issue.
