### ISSUE TITLE
Collection grid not showing summary text

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#794]
The collection grid is only showing the title of the collection item page. It should be showing the title and summary of the collection item page as it does on the current site:

Current site: https://www.colorado.edu/academics
<img width="1381" alt="Screenshot 2024-04-05 at 10 47 13 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/1757082/e4dc1c8d-939a-4824-a332-6765e70c2058">

New site: https://live-ucbdev-sandbox-wendy.pantheonsite.io/academics
<img width="1393" alt="Screenshot 2024-04-05 at 10 47 44 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/1757082/9b29caa8-3443-44b5-b9a7-0236878f3807">
<img width="1162" alt="Screenshot 2024-04-05 at 10 49 04 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/1757082/3ab8b7ad-54da-4b65-99bf-73f32136e2af">

**Comment by jcsparks** [comment]
Looks like the summaries were tagged as hidden in this case : 

<img width="1018" alt="Screenshot 2024-04-09 at 10 42 26 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/12704433/6b58802a-06f2-4830-aa89-db59c3e03179">

**Comment by timurtripp** [comment]
Works as intended
