### ISSUE TITLE
Block styles slow to update on different pages

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#796]
When placing a block on multiple pages and then applying a block style (background color, icon, etc) sometimes the pages don't show the current settings.

This is particularly an issue when the block is placed with Block Layout rather than Layout Builder.  This only seems to update if another edit is made using the Block Layout editor.

Block placed in sidebar and set to a dark gray background:
<img width="1369" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/4a149193-28ef-4cb4-b69a-53d70bd32c43">

Same block on another page, but showing the previous setting of a light gray background:
<img width="1355" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/a0385793-68b9-4fc0-bd31-c0b0a2ea5550">

**Comment by kevincrafts** [comment]
This isn't just with block styles, but also with other configurations, such as changing the number of articles to display in a list, or changing the article display type.

**Comment by jnicholCU** [comment]
I believe this is fixed now. It used to be a caching issue but I'm seeing things get updated in real time now without needing the cache clear.
