### ISSUE TITLE
Too much spacing between blocks in sections

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#820]
Within sections, when multiple blocks are stacked in that section, there is too much vertical space between them. 

Example: Academic page
Current page: https://www.colorado.edu/academics/bs-aerospace-engineering
Sandbox page: https://live-ucbdev-sandbox-wendy.pantheonsite.io/bachelor-science-aerospace-engineering

Main block:
Current:
![Screenshot 2024-04-11 at 9 42 59 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/9cbe3c6f-910c-4362-aeb1-587646ac971f)
Sandbox:
![Screenshot 2024-04-11 at 9 42 53 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/2b0f3301-a7ef-4e21-9ba3-fbc56416bf10)
![Screenshot 2024-04-11 at 9 46 12 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/734fde1c-ff47-4c3e-9ce1-8bbbbd9284e1)

Be successful block:
Current:
![Screenshot 2024-04-11 at 9 50 09 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/10da9334-8622-4f6e-ad44-99e4e336da10)
Sandbox:
![Screenshot 2024-04-11 at 9 50 17 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/4987291c-a197-4bcd-800b-a637fb1da04d)

![Screenshot 2024-04-11 at 9 50 49 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/4f4b0ca9-8540-46a1-9690-1d029fc55e0d)

**Comment by jcsparks** [comment]
watch the gutter settings
