### ISSUE TITLE
Unpublishing a collection item does not remove it from displaying in the collection grid

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#831]
In testing the display of the collection grid I unpublished the Music Library collection item, but it is still displaying even though it is unpublished and it also looks like the collection item page is still live as well (although not sure how to tell if this is the case).

https://live-ucbdev-sandbox-wendy.pantheonsite.io/music-library

![Screenshot 2024-04-12 at 9 46 09 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/7cc3bbc4-396b-4765-8969-ae0056832272)
![Screenshot 2024-04-12 at 9 48 46 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/3f7a1a28-a26a-4ed2-a540-266e8e766a82)
![Screenshot 2024-04-12 at 9 50 35 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/cd0eebd0-6f74-45d4-b606-6d1b572c6f0a)

**Comment by timurtripp** [comment]
It's showing up because you're logged in and have permission to see them. I'm accessing the site as a guest and can't see either of these. Going to the direct link you supplied redirects me to the login page.

**Comment by timurtripp** [comment]
Works as intended
