### ISSUE TITLE
Content alignment in multi-column sections

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#847]
Multi-column sections have additional horizontal padding, resulting in the content on the left not aligning with content that is placed in a single column section.

<img width="781" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/f1a0d3da-0cd5-42a4-90af-470e1751a7d0">

**Comment by jnicholCU** [comment]
Just heinous amounts of misalignment 
<img width="1198" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/94021017/d221273b-6480-43ca-b1c2-e758c75879d5">

**Comment by jnicholCU** [comment]
Going to be a little more work than expected.
