### ISSUE TITLE
Related articles doesn't work in Safari

### ISSUE THREAD

**Issue by TeddyBearX** [CuBoulder/tiamat-theme#85]
Safari seems to be more strict than Chromium with bounding the scope of JavaScript, this is producing undefined variable errors with some of the `const` variables declared.

There are easy fixes for this, but my work on article list could be useful for related articles as well. Feel free to take a look at [this file](https://github.com/CuBoulder/tiamat-theme/blob/issue/59/js/ucb-article-list.js), particularly the class `ArticleProvider`, and see if it would be any use.

Tagging @patrickbrown-io

**Comment by patrickbrown-io** [comment]
@TeddyBearX - Opened a PR for an immediate bug fix on this issue as well as a separate issue #86 for refactoring the block. Self assigned and will complete after the Campus News block
