### ISSUE TITLE
Social Media Icons - Vertical display - Vimeo missing Text

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/tiamat-theme#856]
The Vimeo link is missing its text in the Social Media icons block when you use the vertical display.
![SMlinks-vimeo](https://github.com/CuBoulder/tiamat-theme/assets/16137919/df92bd91-044d-4b05-8310-2ec33f26c93f)

**Comment by timurtripp** [comment]
It does appear to be the case, marking as resolved
