### ISSUE TITLE
Slider Block Titles

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#858]
While rarely used, the titles of slider blocks aren't being styles correctly and are outputting the title settings to the screen:

<img width="1380" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/d4f81e39-f7af-4f68-b271-c2a06e8cca20">

**Comment by timurtripp** [comment]
Duplicate issue: CuBoulder/tiamat-theme#788
