### ISSUE TITLE
Content grid spacing with title link

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#876]
Once a link is added to the title of a content grid, it bumps all the text down and is uneven with the other grid text without the link. 

See "Majors" title vs titles for Minors, Graduate Programs and Certificates
![Screenshot 2024-04-23 at 7 35 15 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/23358bad-91ee-459c-8489-dc0d0fd364b8)

**Comment by jnicholCU** [comment]
@timurtripp Just a heads up this might have been taken care of in my previous grid changes. I'm double checking it after this meeting with Wendy.

**Comment by jnicholCU** [comment]
Yeah this was solved with my previous grid changes.

**Comment by jnicholCU** [comment]
Should be reflected with new sandbox updates 
Resolved #868
