### ISSUE TITLE
Admin Sub-Theme Investigation

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#88]
Need to determine what an admin sub-theme will allow us to do.  A couple of potential improvements we may be able to achieve with an admin sub-theme include : 

- Making the Edit action bar at the top of the screen more conspicuous (perhaps blue with bold white text) 
- Making the Add Content menu more refined, including icons and section breaks or grouping mechanism for related content types

There's other potential areas of improvement, but this is the start.

**Comment by timurtripp** [comment]
Closing this issue as it lacks relevance following the switch to Claro. Future enhancements to the admin interface should be suggested in either the Admin Menus module or the admin sub-theme as applicable.
