### ISSUE TITLE
Add alert background color for block styles

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#880]
Sometimes a site may need to post some sort of alert/notification, such as a deadline postponement, event cancellation, etc.

These are different than the campus alerts that display at the top of the page and should be designed differently and placed as a regular block.  Within the style guide there's a light red color that I think would work for this: https://styleguide.colorado.edu/colors (#FFEBEE).  Link colors should be tested/adjusted if necessary to maintain accessible color contrast.

Also, I'd suggest naming/labelling this background as "Alert" so site editors know what the color should be used for rather than using it for something else.

**Comment by patrickbrown-io** [comment]
Spoke with Kevin, just add this to "Text Block" for now since the intent is to use only as an alert/notification rather than a site style.

**Comment by patrickbrown-io** [comment]
This will affect all blocks so we need to see how to handle this
