### ISSUE TITLE
Link to section

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#885]
There's quite a few sites that link to sections on a page via the block ID. Since these IDs no longer exist we should explore ways to continue this functionality.

It looks like this module would allow editors to give a name/id to a section or block in layout builder which would also allow for better id names than programatically generated ones: https://www.drupal.org/project/layout_builder_ids

**Comment by jcsparks** [comment]
We're not using vanilla layout builder so a module like this won't work for us.
