### ISSUE TITLE
Taxonomy order

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#887]
Created taxonomy for "Collection Category". As added to the taxonomy, the order was no longer alphabetical. Selected "Reset to Alphabetical" under Structure, Taxonomy, but change of order was not reflected on the page with the Collection Grid with those filters.

https://live-ucbdev-homepage.pantheonsite.io/admin/structure/taxonomy/manage/collection_category/overview
![Screenshot 2024-04-24 at 11 51 44 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/f36bfa90-9f54-4811-a5e2-1ffa4080ffa1)

https://live-ucbdev-homepage.pantheonsite.io/academics/programs/majors
![Screenshot 2024-04-24 at 11 53 17 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/b4603ac9-ca60-4573-8186-305725bffd8b)

**Comment by jcsparks** [comment]
Cachine issue
