### ISSUE TITLE
A11Y : People List Page

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#902]
When the Filters are exposed on the rendered page, there's no obvious way for a person on a screen reader to know when the new content has been added and where that content starts.  

I believe we'll have to put in some aria-only text whenever we update the page to let people know where the new content starts and a sense for how many new elements were added to the page.   

Will try to track down some documentation on best practices here.  

Ideally, I believe we would also have something that would set focus to the newly added/updated content as well.

**Comment by timurtripp** [comment]
This is a good wider discussion to have in terms of web development best practices, let me know what you're able to find.
