### ISSUE TITLE
A11Y : Content Grid Content with Images

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#905]
The DOM order of content matters.  Visually these are displaying properly but we want the content to be rendered with the image as the first element and the image after it, this is especially true of the text relates to the image.  

DAO reports that users often would mis identify which image went with which piece of text because the convention was not followed.  

Kevin recommend that Images in content grids are always going to render above the content we should place the content in the DOM in the correct semantic order (i.e. Title, Image) and then use flexbox ordering to reverse them visually on the page.  

Additionally we often have multiple links to the same piece of original content from the content aggregator.  E.G. the image links to original source, the title also links to the original source.  In most cases where we have multiple links for sighted users we want there to be one primary link for people using screen readers so they don't have to listen to the same link being read to them over and over.  Make the tile the primary link and add `role="presentation" aria-hidden="true"` to the anchor tag around the image in this case.

**Comment by timurtripp** [comment]
I can eliminate some of the multiple links and put both the title and image under the same link. This works better for the visual hover states as well.

**Comment by timurtripp** [comment]
Will need to determine how the "Offset" layout works next week and do that one. I'm not actually sure how it's supposed to work.
