### ISSUE TITLE
Collection item on collection grid, changes text colors when collection grids stacked on page

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#930]
See ticket #929. I'm not sure if the issues with the gold and white text is because of the dark gray background, because now I'm noticing the grid section below it with the light gray background is also showing gold and white text. On this page:

https://live-ucbdev-homepage.pantheonsite.io/academics/arts-sciences

![Screenshot 2024-05-06 at 2 36 53 PM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/dc1ccafa-ba22-4a15-9a5a-6d8b3b896012)

**Comment by timurtripp** [comment]
Related: CuBoulder/tiamat-theme#948
