### ISSUE TITLE
A11Y : Article List and Article Blocks 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#932]
Whenever we have a "Read more" link related to articles we are correctly adding in additional context to the link with a `sr-only` tag to make it read something like "Read more about the article title". 

This is the desired behavior however, screen readers are not catching the space between the visual "read more" link and the span with the sr-only tag that has " about the article title".  

Working hypothesis is that the screen reader software is running the equivalent of a trim on this content and stripping out the whitespace character.  We're going to try replacing the space character at the start of the span with a `&nbsp;` HTML equivalent to see if that works better for the screen readers.  

Example here : https://live-ucbdev-sandbox-a11y.pantheonsite.io/article-feature

**Comment by timurtripp** [comment]
Hey @jcsparks, we already added an `aria-hidden="true"` to that read more link as requested in your issue CuBoulder/tiamat-theme#900. Do you want the `aria-hidden="true"` taken off, or do you want the `sr-only` element removed as it serves no function inside an `aria-hidden="true"`?
