### ISSUE TITLE
Article grid block thumbnails not displaying the correct image style

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#936]
I'm not exactly sure what's happening here so I'll try my best to explain...

I have an article grid block that I added to a page and it appears correct:

<img width="1432" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/ce64b7ce-5d91-4a69-8e49-039e486a0f86">

I then went and made that block reusable and added it to another page. Here's a screenshot after I added it to the new page in layout builder:

<img width="1390" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/f7f29e3d-943d-4770-8978-18ca003af063">

But when I save the layout and view the page, the thumbnails now display as squares instead of the 2:1 rectangles:

<img width="1404" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/a564fe66-3c36-4e2c-b713-482d59f47669">

Updating the block does not fix the issue.

The original page still shows the 2:1 rectangles.

**Comment by patrickbrown-io** [comment]
@kevincrafts -- I cannot replicate this in a dev environment or your sandbox site following the above steps. The issue also appears to be resolved on your sandbox site as the images are all showing correctly on these blocks on the pages I could find it on.
