### ISSUE TITLE
Sandbox Breadcrumbs Issues

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#941]
Breadcrumbs are only showing up on sandbox sites after a cache clear. 
After some time the breadcrumbs disappear again. Usually done by going to a new page and then returning to the previous.
This is a problem in the content checking logic most likely. 
<img width="540" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/94021017/0cf1ee32-d25c-4f9b-954b-9212725938b7">
<img width="495" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/94021017/1bf7151e-a502-450d-86c5-8f4754e3e052">
<img width="485" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/94021017/44772d06-39ac-463a-ae59-296be6467c4a">

**Comment by jnicholCU** [comment]
It is not tied to the check. Might be the preprocess on the cache tags in the site configuration modue?

**Comment by jcsparks** [comment]
Fixed in #947
