### ISSUE TITLE
Collection Grid/Layout Builder Nesting issue

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#948]
It seems like there is a bug in the collection grid that causes a nesting issue in Layout Builder. 
Two column sections get merged into a single column. I believe this is because of a missing closing tag in the collection grid.

<img width="1385" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/94021017/a12a46a1-cafd-472e-9fb5-227f2ab67a38">

**Comment by timurtripp** [comment]
Related: CuBoulder/tiamat-theme#930
