### ISSUE TITLE
Breadcrumbs based on url alias

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/tiamat-theme#955]
As per Wendy, the urls are often shortened using the aliases so so that they can be accessed easier. 
Sometimes the url is made so that it targets a different parent page rather than it's actual file structure. 
It looks like the breadcrumbs follows the url alias rather than actual structure which the current site doesn't do. 
Something to look in to.

<img width="1073" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/94021017/fc5aa481-9744-4c82-8159-be9cc752709d">

**Comment by jcsparks** [comment]
Need to have a discussion with the UI/UX team to explain what's possible and how they want it to work.
