### ISSUE TITLE
Article feed returning API error

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#971]
An article list block on my sandbox site (at the bottom of https://live-ucbdev-sandbox-kevin.pantheonsite.io/top-level-page) is now displaying an API error instead of the list of articles it was showing:

<img width="657" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/7b87ab56-88e5-4fa4-890c-053d8ab8b991">

**Comment by patrickbrown-io** [comment]
Caused by an Article having no summary or no content body.
