### ISSUE TITLE
Restricted permissions in Collection Item grid display tab

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#992]
Went back into an already created collection item to update information int the Grid Display section. I'm locked out of editing because it says I don't have the permissions to make changes. I'm able to edit other parts of this collection item. I've only had this happen on this collection item that I've gone back to edit. Other collection items aren't showing this. 

https://live-ucbdev-homepage.pantheonsite.io/node/35/edit?destination=/admin/content%3Ftitle%3D%26type%3Dcollection_item_page%26status%3DAll%26langcode%3DAll%26order%3Dtitle%26sort%3Dasc

![Screenshot 2024-05-21 at 9 19 02 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/ce2b30d0-3ea6-4590-bb29-b138bc571f11)

**Comment by jcsparks** [comment]
Wendy unable to replicate, will close if the issue pops up again.
