### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#996]
We're going to add Google Translate to all sites.  The setup through Google will require someone to add a credit card to pay for the service fees but we'll coordinate with Erin to make that happen when it's ready.  

We should be able to add and configure the JS code to the sites to make this ready to go at this point though.  

I think this is the correct starting place to add it in : https://cloud.google.com/translate?hl=en

**Comment by jcsparks** [comment]
Essentially they want it to work like the translate tab at the top of : https://www.cu.edu/

**Comment by kevincrafts** [comment]
I can work on some mockups for this for how it should fit into the rest of the site.
